### PR TITLE
Adds vagrant-bindfs support

### PR DESCRIPTION
**Pull request by tomjn**
## Checks

 - [ ] I've tested this PR with Vagrant **vXX** and VirtualBox **vXX** on **Operating System**
 - [x] This PR is for the `develop` branch not the `master` branch
 - [ ] I've updated the changelog
 - [ ] This PR is complete and ready for review

### CODE REVIEW

**Comment by tomjn** [comment]
This mostly helps with handling permissions. I did hope initially it would give a performance boost for file system access but I'm not so sure now, testing and benchmarking needs to be done, I'm punting this off to 2.6+

**Comment by Mte90** [comment]
I don't have an OSX environment to do a test

**Comment by tomjn** [comment]
I've yet to test it mysql so I'm in no rush, but I do notice that some users of other similar projects have done this

**Comment by Mte90** [comment]
Updated the pr so we can test it

**Comment by tomjn** [comment]
Note that I created this PR in hopes it would improve performance, it's not a fix for VVV3 mariadb issues

**Comment by tomjn** [comment]
Since this doesn't do what I originally hoped for, I'm going to close this PR

**Pull request closed without merging**
