### PR TITLE
Allow symlinks in shared folders (in VirtualBox)

### PR DESCRIPTION
**Pull request by cfoellmann**
Not allowing symlinks in the first place is a security/stability safety. SInce this is for development it should be possible.

MIght need additional changes for Parallels + Fusion

---

New PR (replaces #592) to change destination branch to `develop`

### CODE REVIEW

**Comment by cfoellmann** [comment]
scratch the feedback. doesnt work now

**Comment by jeremyfelt** [comment]
Hi @cfoellmann, sorry I've never gotten around to testing this.

I'm okay having a solution only for VirtualBox if that's all we're able to support. Can you walk me through the best way to take advantage of this locally?

**Comment by LoreleiAurora** [comment]
Symlinks that don't spread outside of a shared folder already work so personally i dont feel this adds anything we cant already do.

Rather than using symlinks i would use the local_dir in vvv-config.yml to move a site out of the www dir, and/or allow a Customfile in the site and set up another shared folder to map for example a plugin outside of www.

**Comment by jeremyfelt** [comment]
I'm going to go ahead and close this out for now. If this is still needed, let's go ahead and discuss the problem and approach in a new issue and then go for another attempt.

**Pull request closed without merging**
