### PR TITLE
fix #1876 - remove nvm

### LINKED ISSUE #1876: NPM update issues
@tomjn now xedug traces are not created automatically anymore, but I got this series of errors when provisioning

```
default: Cleaning apt caches...
    default: Installing/updating npm...
    default: npm
    default:  ERR! path /usr/bin/npm
    default: npm ERR! code EACCES
    default: npm
    default:
    default: ERR! errno -13
    default: npm ERR! syscall unlink
    default: npm ERR! Error: EACCES: permission denied, unlink '/usr/bin/npm'
    default: npm ERR!  { [OperationalError: EACCES: permission denied, unlink '/usr/bin/npm']
    default: npm ERR!   cause:
    default: npm ERR!    { [Error: EACCES: permission denied, unlink '/usr/bin/npm']
    default: npm ERR!
    default:       errno: -13,
    default: npm ERR!      code: 'EACCES',
    default: npm ERR!      syscall: 'unlink',
    default: npm ERR!      path: '/usr/bin/npm' },
    default: npm ERR!   stack: "Error: EACCES: permission denied, unlink '/usr/bin/npm'",
    default: npm ERR!   errno: -13,
    default: npm ERR!
    default:    code: 'EACCES',
    default: npm
    default: ERR!   syscall: 'unlink',
    default: npm
    default:  ERR!   path: '/usr/bin/npm' }
    default: npm
    default: ERR!
    default: npm ERR! The operation was rejected by your operating system.
    default: npm ERR! It is likely you do not have the permissions to access this file as the current user
    default: npm ERR!
    default: npm ERR! If you believe this might be a permissions issue, please double-check the
    default: npm
    default:  ERR! permissions of the file and its containing directories, or try running
    default: npm ERR! the command again as root/Administrator (though this is not recommended).
    default: npm ERR! A complete log of this run can be found in:
    default: npm ERR!     /home/vagrant/.npm/_logs/2019-06-20T14_28_40_849Z-debug.log
    default: Installing/updating npm-check-updates...
    default: npm
    default:  ERR! path /usr/bin/ncu
    default: npm
    default:
    default: ERR! code EACCES
    default: npm
    default:
    default: ERR! errno
    default:  -13
    default: npm
    default:  ERR! syscall unlink
    default: npm
    default:  ERR! Error: EACCES: permission denied, unlink '/usr/bin/ncu'
    default: npm ERR!  { [OperationalError: EACCES: permission denied, unlink '/usr/bin/ncu']
    default: npm ERR!   cause:
    default: npm ERR!    { [Error: EACCES: permission denied, unlink '/usr/bin/ncu']
    default: npm
    default: ERR!      errno: -13,
    default: npm ERR!
    default:       code: 'EACCES',
    default: npm ERR!
    default:       syscall: 'unlink',
    default: npm
    default: ERR!      path: '/usr/bin/ncu' },
    default: npm
    default: ERR!
    default:    stack: "Error: EACCES: permission denied, unlink '/usr/bin/ncu'",
    default: npm ERR!   errno: -13,
    default: npm
    default: ERR!   code: 'EACCES',
    default: npm
    default: ERR!
    default:    syscall: 'unlink',
    default: npm ERR!   path: '/usr/bin/ncu' }
    default: npm
    default:  ERR!
    default:
    default: npm ERR!
    default:  The operation was rejected by your operating system.
    default: npm ERR!
    default:  It is likely you do not have the permissions to access this file as the current user
    default: npm ERR!
    default: npm ERR! If you believe this might be a permissions issue, please double-check the
    default: npm
    default: ERR!
    default:  permissions of the file and its containing directories, or try running
    default: npm ERR! the command again as root/Administrator (though this is not recommended).
    default: npm ERR!
    default:  A complete log of this run can be found in:
    default: npm ERR!     /home/vagrant/.npm/_logs/2019-06-20T14_28_52_186Z-debug.log
    default: ack-grep already installed
```

_Originally posted by @kmgalanakis in https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1866#issuecomment-504051848_

### PR DESCRIPTION
**Pull request by Mte90**
I am testing it right now with https://github.com/Varying-Vagrant-Vagrants/custom-site-template-develop/pull/14

### CODE REVIEW

**Comment by tomjn** [comment]
hmmm do we need to do something to `npm` to make sure the linkage is undone and put back how it's supposed to be? perhaps `nvm use system`?

**Comment by Mte90** [comment]
it is not enough because the permission on npm are not right and I have to rebase it.

**Comment by Mte90** [comment]
The problem is that require a vagrant destroy because apt will not downgrade the nodejs version because the 11 is already used.

**Comment by tomjn** [comment]
@Mte90 can we just check the node version? If it's 11, apt uninstall, do an apt update, then reinstall?

**Comment by Mte90** [comment]
manually yes it is possible but in case people has troubles we a destroy is more easy (sure at this point the nvm check is not required anymore).

**Comment by tomjn** [comment]
This was done in #1880

**Pull request merged**
