### PR TITLE
Site git folders

### PR DESCRIPTION
**Pull request by tomjn**
This PR lets sites specify git repos and folders to clone them to.

For example, in theory this creates a VIP Go site with the VIP Go skeleton:

```yaml
  vipone:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - vipone.test
    git:
      public_html/wp-content/:
        repo: https://github.com/Automattic/vip-go-skeleton.git
        overwrite: true # delete wp-content if it is not a git repo
      public_html/wp-content/mu-plugins:
        repo: https://github.com/Automattic/vip-go-mu-plugins.git
        overwrite: true # delete wp-content/mu-plugins if it is not a git repo
        forcepull: true # on provision hard reset, discard local changes, and pull down the latest version
```

## Checks

* [x] I've updated the changelog.
* [x] I've tested this PR
* [x] This PR is for the `develop` branch not the `stable` branch.
* [x] This PR is complete and ready for review.

### CODE REVIEW

**Comment by tomjn** [comment]
I'm testing this PR out with this site in `config.yml`:

```yaml
  vipone:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - vipone.test
    git:
      public_html/wp-content/:
        repo: https://github.com/Automattic/vip-go-skeleton.git
        overwrite: true
        forcepull: true
      public_html/wp-content/mu-plugins:
        repo: https://github.com/Automattic/vip-go-mu-plugins.git
```

**Comment by tomjn** [comment]
I've refactored in hopes of a more futureproof schema such as this:

```yaml
  vipone:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - vipone.test
    folders:
      public_html/wp-content/:
        git:
          repo: https://github.com/Automattic/vip-go-skeleton.git
          overwrite: true
      public_html/wp-content/mu-plugins:
        git:
          repo: https://github.com/Automattic/vip-go-mu-plugins.git
          overwrite: true
          forcepull: true
```

**Comment by Mte90** [comment]
Seems an interesting proposal, we need to do also a bit of documentation for that I guess.
Maybe `force_pull` is better?

**Comment by Mte90** [comment]
Probably an example in the default config is required?

**Comment by tomjn** [comment]
I split force_pull into `pull` and `hardreset`, and `overwrite` is now `overwrite_on_clone`

**Review by Mte90 — APPROVED** [review]

**Pull request merged**
