### PR TITLE
Adds mailcatcher support.

### PR DESCRIPTION
**Pull request by EHLOVader**
This PR replaces #464 

This is based off of the `develop` branch and should be used instead.

Includes:
 RVM install
 mailcatcher install
 startup script
 PHP smtp configuration
 dashboard link to port

Later revisions also did the following:
 Fixes issues with signature checks in the RVM installation process.
 Removed the stopgap fix for i18n dependency issues of past.
 Added blank lines per request.

### CODE REVIEW

**Comment by dwainm** [comment]
@EHLOVader this branch works. Thanks for all the effort, kudos to you. I hope it gets into master soon.

**Comment by jdevalk** [comment]
Works like a charm. Great work @EHLOVader, please merge @jeremyfelt :)

**Comment by hlashbrooke** [comment]
+1 to this - would love to see this in master soon :)

**Comment by cfoellmann** [comment]
@EHLOVader please edit your main comment and add `Close #337` so it will close #337 automatically on merge

**Comment by cfoellmann** [comment]
:+1: for merge

**Comment by tacoverdo** [comment]
:+1:

**Comment by jeremyfelt** [comment]
Thanks for all the great work @EHLOVader! And thanks to everyone for testing this out here and in #464. :)

Things seem to be working great after provisioning. I started with a fresh VM on `develop` and then did `vagrant provision` with this pull request applied. It added about 5 minutes because of the extra Ruby download, but that's not too bad. It would be nice to find a way to speed it up in the future if possible.

After merge I'm going to play with a few things:

* Attempt to silence the `gem install` that (I think) is generating the ruby download messaging. Because of how Vagrant displays the messaging, this creates a wall of red. Though silencing will create a wall of silence. We'll see. :)
* Look into what binding to `0.0.0.0` implies. It would be nice if we could bind to a specific address to avoid possible security issues, especially if someone has converted their box to a public IP for use with external testing.
* We're doing version detecting in a few places now for a couple things. We should be able to abstract this as a separate function to clean up provision.sh a bit.

**Pull request merged**
