### PR TITLE
Switch from triggers to a pre and post provisioner for provision triggers

### PR DESCRIPTION
**Pull request by tomjn**
This fixes `vagrant up --provision` and `vagrant reload --provision` in Vagrant v2.2.14, needs testing

## Checks

* [ ] I've updated the changelog.
* [ ] I've tested this PR
* [x] This PR is for the `develop` branch not the `stable` branch.
* [ ] This PR is complete and ready for review.

### CODE REVIEW

**Comment by tomjn** [comment]
Closes #2306

**Comment by tomjn** [comment]
This will likely mean duplicate teddy bears when running `vagrant up --provision` which needs resolving

**Comment by tomjn** [comment]
Also makes sudo warnings more prominent ( #2311 )

**Review by Mte90 — APPROVED** [review]
I tested and I like the new colors

**Pull request merged**
