### PR TITLE
Update MySQL to 5.7

### LINKED ISSUE #928: Upgrade MySQL to 5.6
One of the minimum requirements for WordPress is MySQL 5.6.

Ubuntu 14.04 still has the default version at 5.5 but 5.6 is available in the default repositories.
I changed provision/provision.sh line 59 from mysql-server to mysql-server-5.6 then did a vagrant provision to get it updated.
So far everything is running well without any problems.

### PR DESCRIPTION
**Pull request by LoreleiAurora**
Fixes #928

### CODE REVIEW

**Comment by johnjamesjacoby** [comment]
See also #876 to consider using MariaDB instead.

**Comment by moorscode** [comment]
When trying these changes in a test vagrant I get the following output:

```
==> default: GPG error: http://ppa.launchpad.net trusty InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 4F4EA0AAE5267A6C
```

Which breaks the installation and leaves the Vagrant without MySQL package being installed (among other packages).

**Comment by jeremyfelt** [comment]
I've created https://github.com/Varying-Vagrant-Vagrants/VVV/issues/876 to discuss this further.

**Comment by moorscode** [comment]
#949 instead of 876.

**Comment by ottok** [comment]
Please avoid using PPAs. Stick to the packages in official Ubuntu repositories for best quality, security are reliability.

**Comment by RobertoSnap** [comment]
We have formerly used [PHP 7 Rasmus vagrant](https://github.com/rlerdorf/php7dev) for our local development enviroments. Decided to switch to VVV. Had to use this pull so we could import our databases with utf8mb4_unicode_ci collation.

**Pull request closed without merging**
