### PR TITLE
Update VM image to Ubuntu 18.04 LTS Bionic 

### PR DESCRIPTION
**Pull request by av3nger**
## Summary:

An update to the VM box. I've only tested on the VirtualBox provider on the latest MacOS. Should be tested on other providers as well.
- Update VM box from ubuntu/trusty64 to ubuntu/cosmic64
- Resolve various warnings during `vagrant up`

## Checks

 - [x] I've tested this PR with Vagrant **2.2.3** and VirtualBox **6.0.0** on **MacOS 10.14.2**
 - [x] This PR is for the `develop` branch not the `master` branch
 - [ ] I've updated the changelog
 - [ ] This PR is complete and ready for review

### CODE REVIEW

**Comment by tomjn** [comment]
Thanks for this, but this leads to a longstanding problem that has stopped us just updating the box in the past.

The problem is that the database was moved out of a mounted shared folder, and into the VM to improve performance when VVV 2 was released. Now, if we merged this, on the next provision everybody would be updated, wiping their local databases in the process.

If it weren't for this we'd have switched to Ubuntu 16 a long time ago. Moving to 16 was intended for VVV 3, which was planned to be pre-built via CI so that you could `vagrant box update` on a regular basis making it faster to provision and easier to keep up with newer distro releases.

For the moment I think a mechanism for migrating the database storage from `/srv/database` to `/vagrant/database` in such a way that it doesn't break for existing users would be good. Once that's done, PR's like this no longer need to fear data loss as a side effect. This does mean that we'll need a few things:

 - If no existing VM exists, use Ubuntu 18
 - If the database is already mapped to a shared folder, switch to Ubuntu 18
 - If a VM exists, and it's using Ubuntu 14, try to migrate the database folder so that on the next provision, it upgrades to 18

**Comment by av3nger** [comment]
@tomjn , yeah, I read on some PR or issue ticket that there were problems with migrating. So far I only posted this as solution for a clean Ubuntu 18 install and something we can expand on. I haven't tried migrating yet, but I do plan to try it out in the upcoming days.

`rsync` is a good idea, definitely worth a try. I would also, maybe, consider exporting via `wp cli` or directly with `mysqldump` with `--routines` flag to export stored procedures. And storing a backup just in case something goes wrong. That way there will always be a manual way to restore.

**Comment by tomjn** [comment]
I spoke with @LoreleiAurora over the weekend, and a move to 18 is needed in the longrun, I'm still concerned about breaking things for existing users, ideally they should be able to upgrade with:

```
git pull
vagrant destroy --force
vagrant up --provision
```

But I'm concerned about data loss and would like the database thing sorted, preferably sooner rather than later. The question is, how do we migrate VMs that have their DB stored inside the VM, to instead store it in a mount, without destroying or making that data inaccessible?

**Comment by av3nger** [comment]
@tomjn , yeah, I was able to confirm the data loss. Don't think it will be a big problem to solve this issue, though. Unfortunately, I haven't had time to take a closer look at it yet. But I still plan to in the upcoming week or two.

**Comment by Mte90** [comment]
Maybe we can do a script that is executed only on when there is the bump of the distro.
In that way we can do a full backup of the database to reimport later and add other integrations in case we need it.

**Comment by tomjn** [comment]
I've adjusted the PR to use the 18.04 LTS Bionic distribution rather than 18.10 Cosmic

**Comment by tomjn** [comment]
Testing:

```sh
git clone -b ubuntu-cosmic git@github.com:av3nger/VVV.git bionic
cd bionic
vagrant up --provision
```

cleanup:

```sh
vagrant halt
vagrant destroy --force
cd ..
rm -rf bionic
```

**Comment by tomjn** [comment]
Notes:

 - Mariadb is failing to provision on a mounted folder
 - there's a tallylog warning that happens a lot, it doesn't impact the provisioning but it would be nice to eliminate
 - some cleanup of the old service startup files is a nice to have now that it's using `systemctl` instead

As soon as mariadb provisioning is fixed, we're merging this into `develop` and prepping to a `v3` release. It'd be nice to use the barebones box @LoreleiAurora built as well but not a requirement

**Comment by tomjn** [comment]
I believe setting the log folder permissions to 644/655 might have fixed the tallylog issue

the mysql error log indicates:

```
2019-05-05 12:43:45 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2019-05-05 12:43:45 0 [Note] InnoDB: Waiting for purge to start
2019-05-05 12:43:45 0 [Note] InnoDB: 10.3.14 started; log sequence number 1603977; transaction id 9
2019-05-05 12:43:45 0 [Note] Plugin 'FEEDBACK' is disabled.
2019-05-05 12:43:45 0 [ERROR] Could not open mysql.plugin table. Some plugins may be not loaded
2019-05-05 12:43:45 0 [Note] Recovering after a crash using tc.log
2019-05-05 12:43:45 0 [ERROR] Can't init tc log
2019-05-05 12:43:45 0 [ERROR] Aborting
```

**Comment by tomjn** [comment]
Current state of provisioning fails with:

<details>

```
    default: Setting up gcc (4:7.4.0-1ubuntu2.2) ...
    default: Setting up mariadb-server-10.3 (1:10.3.14+maria~bionic) ...
    default: 2019-05-05 13:35:50 0 [Note] /usr/sbin/mysqld (mysqld 10.3.14-MariaDB-1:10.3.14+maria~bionic) starting as process 5529 ...
    default: 2019-05-05 13:35:50 0 [Warning] Setting lower_case_table_names=2 because file system for /var/lib/mysql/ is case insensitive
    default: 2019-05-05 13:35:50 0 [Note] InnoDB: Using Linux native AIO
    default: 2019-05-05 13:35:50 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
    default: 
    default: 2019-05-05 13:35:50 0 [Note] InnoDB: Uses event mutexes
    default: 2019-05-05 13:35:50 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
    default: 2019-05-05 13:35:50 0 [Note] InnoDB: Number of pools: 1
    default: 2019-05-05 13:35:50 0 [Note] InnoDB: Using SSE2 crc32 instructions
    default: 2019-05-05 13:35:50 0 [Note] InnoDB: Initializing buffer pool, total size = 256M, instances = 1, chunk size = 128M
    default: 2019-05-05 13:35:50 0 [Note] InnoDB: Completed initialization of buffer pool
    default: 2019-05-05 13:35:50 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
    default: 2019-05-05 13:35:50 0 [Warning] InnoDB: Failed to set O_DIRECT on file./ibdata1; OPEN: Invalid argument, continuing anyway. O_DIRECT is known to result in 'Invalid argument' on Linux on tmpfs, see MySQL Bug#26662.
    default: 2019-05-05 13:35:50 0 [Note] InnoDB: Header page consists of zero bytes in datafile: ./ibdata1, Space ID:0, Flags: 0
    default: 2019-05-05 13:35:50 0 [ERROR] InnoDB: Corrupted page [page id: space=0, page number=0] of datafile './ibdata1' could not be found in the doublewrite buffer.
    default: 2019-05-05 13:35:50 0 [ERROR] InnoDB: Plugin initialization aborted with error Data structure corruption
    default: 2019-05-05 13:35:51 0 [Note] InnoDB: Starting shutdown...
    default: 2019-05-05 13:35:51 0 [ERROR] Plugin 'InnoDB' init function returned error.
    default: 2019-05-05 13:35:51 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
    default: 2019-05-05 13:35:51 0 [Note] Plugin 'FEEDBACK' is disabled.
    default: ERROR: 1146  Table 'mysql.user' doesn't exist
    default: 2019-05-05 13:35:51 0 [ERROR] Aborting
    default: Configuring mariadb-server-10.3
    default: -------------------------------
    default: 
    default: Unable to set password for the MariaDB "root" user
    default: 
    default: An error occurred while setting the password for the MariaDB administrative 
    default: user. This may have happened because the account already has a password, or 
    default: because of a communication problem with the MariaDB server.
    default: 
    default: You should check the account's password after the package installation.
    default: 
    default: Please read the /usr/share/doc/mariadb-server-10.3/README.Debian file for 
    default: more information.
    default: Created symlink /etc/systemd/system/mysql.service → /lib/systemd/system/mariadb.service.
    default: Created symlink /etc/systemd/system/mysqld.service → /lib/systemd/system/mariadb.service.
    default: Created symlink /etc/systemd/system/multi-user.target.wants/mariadb.service → /lib/systemd/system/mariadb.service.
    default: Job for mariadb.service failed because the control process exited with error code.
    default: See "systemctl status mariadb.service" and "journalctl -xe" for details.
    default: invoke-rc.d: initscript mysql, action "start" failed.
    default: ● mariadb.service - MariaDB 10.3.14 database server
    default:    Loaded: loaded (/lib/systemd/system/mariadb.service; enabled; vendor preset: enabled)
    default:   Drop-In: /etc/systemd/system/mariadb.service.d
    default:            └─migrated-from-my.cnf-settings.conf
    default:    Active: failed (Result: exit-code) since Sun 2019-05-05 13:35:54 UTC; 9ms ago
    default:      Docs: man:mysqld(8)
    default:            https://mariadb.com/kb/en/library/systemd/
    default:   Process: 6189 ExecStart=/usr/sbin/mysqld $MYSQLD_OPTS $_WSREP_NEW_CLUSTER $_WSREP_START_POSITION (code=exited, status=1/FAILURE)
    default:   Process: 6043 ExecStartPre=/bin/sh -c [ ! -e /usr/bin/galera_recovery ] && VAR= ||   VAR=`/usr/bin/galera_recovery`; [ $? -eq 0 ]   && systemctl set-environment _WSREP_START_POSITION=$VAR || exit 1 (code=exited, status=0/SUCCESS)
    default:   Process: 6019 ExecStartPre=/bin/sh -c systemctl unset-environment _WSREP_START_POSITION (code=exited, status=0/SUCCESS)
    default:   Process: 6006 ExecStartPre=/usr/bin/install -m 755 -o mysql -g root -d /var/run/mysq
    default: ld (code=exited, status=0/SUCCESS)
    default:  Main PID: 6189 (code=exited, status=1/FAILURE)
    default:    Status: "MariaDB server is down"
    default: dpkg: error processing package mariadb-server-10.3 (--configure):
    default:  installed mariadb-server-10.3 package post-installation script subprocess returned error exit status 1
    default: Setting up php-xdebug (2.7.1+2.5.5-1+ubuntu18.04.1+deb.sury.org+1) ...
    default: Setting up subversion (1.9.7-4ubuntu1) ...
    default: Setting up libxt6:amd64 (1:1.1.5-1) ...
    default: Setting up g++ (4:7.4.0-1ubuntu2.2) ...
    default: update-alternatives: 
    default: using /usr/bin/g++ to provide /usr/bin/c++ (c++) in auto mode
    default: dpkg: dependency problems prevent configuration of mariadb-server:
    default:  mariadb-server depends on mariadb-server-10.3 (>= 1:10.3.14+maria~bionic); however:
    default: 
    default:   Package mariadb-server-10.3 is not configured yet.
    default: 
    default: dpkg: error processing package mariadb-server (--configure):
    default:  dependency problems - leaving unconfigured
    default: Setting up git-svn (1:2.21.0-0ppa1~ubuntu18.04.1) ...
    default: No apport report written because the error message indicates its a followup error from a previous failure.
    default: Setting up libgs9:amd64 (9.26~dfsg+0-0ubuntu0.18.04.8) ...
    default: Setting up php-memcached (3.1.3+2.2.0-1+ubuntu18.04.1+deb.sury.org+1) ...
    default: Setting up fontconfig (2.12.6-0ubuntu2) ...
    default: Regenerating fonts cache... 
    default: done.
    default: Setting up libtool (2.4.6-2) ...
    default: Setting up php7.2-gd (7.2.18-1+ubuntu18.04.1+deb.sury.org+1) ...
    default: 
    default: Creating config file /etc/php/7.2/mods-available/gd.ini with new version
    default: Setting up php7.2-dev (7.2.18-1+ubuntu18.04.1+deb.sury.org+1) ...
    default: update-alternatives: using /usr/bin/php-config7.2 to provide /usr/bin/php-config (php-config) in auto mode
    default: update-alternatives: using /usr/bin/phpize7.2 to provide /usr/bin/phpize (phpize) in auto mode
    default: Setting up libcairo2:amd64 (1.15.10-2ubuntu0.1) ...
    default: Setting up libmagickcore-6.q16-3:amd64 (8:6.9.7.4+dfsg-16ubuntu6.4) ...
    default: Setting up build-essential (12.4ubuntu1) ...
    default: Setting up ghostscript (9.26~dfsg+0-0ubuntu0.18.04.8) ...
    default: Setting up libxmu6:amd64 (2:1.1.2-2) ...
    default: Setting up libpango-1.0-0:amd64 (1.40.14-1ubuntu0.1) ...
    default: Setting up libmagickwand-6.q16-3:amd64 (8:6.9.7.4+dfsg-16ubuntu6.4) ...
    default: Setting up libxaw7:amd64 (2:1.0.13-1) ...
    default: Setting up php-imagick (3.4.3-4+ubuntu18.04.1+deb.sury.org+1) ...
    default: Setting up imagemagick-6.q16 (8:6.9.7.4+dfsg-16ubuntu6.4) ...
    default: update-alternatives: using /usr/bin/compare-im6.q16 to provide /usr/bin/compare (compare) in auto mode
    default: update-alternatives: using /usr/bin/compare-im6.q16 to provide /usr/bin/compare-im6 (compare-im6) in auto mode
    default: update-alternatives: using /usr/bin/animate-im6.q16 to provide /usr/bin/animate (animate) in auto mode
    default: update-alternatives: 
    default: using /usr/bin/animate-im6.q16 to provide /usr/bin/animate-im6 (animate-im6) in auto mode
    default: update-alternatives: 
    default: using /usr/bin/convert-im6.q16 to provide /usr/bin/convert (convert) in auto mode
    default: update-alternatives: using /usr/bin/convert-im6.q16 to provide /usr/bin/convert-im6 (convert-im6) in auto mode
    default: update-alternatives: 
    default: using /usr/bin/composite-im6.q16 to provide /usr/bin/composite (composite) in auto mode
    default: update-alternatives: using /usr/bin/composite-im6.q16 to provide /usr/bin/composite-im6 (composite-im6) in auto mode
    default: update-alternatives: 
    default: using /usr/bin/conjure-im6.q16 to provide /usr/bin/conjure (conjure) in auto mode
    default: update-alternatives: using /usr/bin/conjure-im6.q16 to provide /usr/bin/conjure-im6 (conjure-im6) in auto mode
    default: update-alternatives: using /usr/bin/import-im6.q16 to provide /usr/bin/import (import) in auto mode
    default: update-alternatives: 
    default: using /usr/bin/import-im6.q16 to provide /usr/bin/import-im6 (import-im6) in auto mode
    default: update-alternatives: 
    default: using /usr/bin/identify-im6.q16 to provide /usr/bin/identify (identify) in auto mode
    default: update-alternatives: using /usr/bin/identify-im6.q16 to provide /usr/bin/identify-im6 (identify-im6) in auto mode
    default: update-alternatives: using /usr/bin/stream-im6.q16 to provide /usr/bin/stream (stream) in auto mode
    default: update-alternatives: 
    default: using /usr/bin/stream-im6.q16 to provide /usr/bin/stream-im6 (stream-im6) in auto mode
    default: update-alternatives: using /usr/bin/display-im6.q16 to provide /usr/bin/display (display) in auto mode
    default: update-alternatives: 
    default: using /usr/bin/display-im6.q16 to provide /usr/bin/display-im6 (display-im6) in auto mode
    default: update-alternatives: using /usr/bin/montage-im6.q16 to provide /usr/bin/montage (montage) in auto mode
    default: update-alternatives: 
    default: using /usr/bin/montage-im6.q16 to provide /usr/bin/montage-im6 (montage-im6) in auto mode
    default: update-alternatives: 
    default: using /usr/bin/mogrify-im6.q16 to provide /usr/bin/mogrify (mogrify) in auto mode
    default: update-alternatives: using /usr/bin/mogrify-im6.q16 to provide /usr/bin/mogrify-im6 (mogrify-im6) in auto mode
    default: Setting up libpangoft2-1.0-0:amd64 (1.40.14-1ubuntu0.1) ...
    default: Setting up imagemagick (8:6.9.7.4+dfsg-16ubuntu6.4) ...
    default: Setting up libpangocairo-1.0-0:amd64 (1.40.14-1ubuntu0.1) ...
    default: Setting up libmagickcore-6.q16-3-extra:amd64 (8:6.9.7.4+dfsg-16ubuntu6.4) ...
    default: Setting up libgvc6 (2.40.1-2) ...
    default: Setting up graphviz (2.40.1-2) ...
    default: Setting up dh-strip-nondeterminism (0.040-1.1~build1) ...
    default: Setting up debhelper (11.1.6ubuntu2) ...
    default: Setting up dh-autoreconf (17) ...
    default: Setting up pkg-php-tools (1.35ubuntu1) ...
    default: Processing triggers for ureadahead (0.100.0-21) ...
    default: Processing triggers for libc-bin (2.27-3ubuntu1) ...
    default: Processing triggers for systemd (237-3ubuntu10.21) ...
    default: Processing triggers for rsyslog (8.32.0-1ubuntu4) ...
    default: Processing triggers for ufw (0.36-0ubuntu0.18.04.1) ...
    default: Processing triggers for php7.2-fpm (7.2.18-1+ubuntu18.04.1+deb.sury.org+1) ...
    default: Errors were encountered while processing:
    default:  mariadb-server-10.3
    default:  mariadb-server
    default: E
    default: : 
    default: Sub-process /usr/bin/dpkg returned an error code (1)
    default: Main packages check and install failed, halting provision
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
~/dev/www/bionic git::ubuntu-cosmic* 
❯ 
```

</details>

**Comment by benlumia007** [comment]
are we keeping mariadb server for the new VM 18.04 LTS,

**Comment by benlumia007** [comment]
i think when you use latest version of mariadb or mysql server ,  it tends to use plugin authorization instead of mysql_native_password. so by changing the mysql_native_password for mysql is 
`ALTER USER 'root'@'localhost' IDENTIFIED WITH 'mysql_native_password' BY 'root'`

I'm not sure how you would change that with mariadb.

**Comment by tomjn** [comment]
That's need the package to successfully install though. We're sticking with
mariadb but we'd have the same issue with mysql

**Comment by tomjn** [comment]
This looks like it works, I'm going to merge into `develop` and begin more stringent testing.

Some notes for the future though:

 - we should aim to eliminate the `/vagrant` synced folder as well as any other nested mounts, it causes issues
 - we don't need `noroot`, the owner of the files will be determined by virtualbox/vagrant, the guest VM has little say in the matter
 - `nvm` is broken, we use a more up to date version of node anyway. Happy for someone to reintroduce it in the core utility, but right now it isn't even being installed and it's been that way for a while
 - omg that was hard, massive props to @LoreleiAurora for helping debug and fix things up, and @av3nger for getting the ball rolling on this

**Pull request merged**
