### PR TITLE
Linting GH Actions

### PR DESCRIPTION
**Pull request by tomjn**
## Checks

 - [ ] I've tested this PR with Vagrant **vXX** and VirtualBox **vXX** on **Operating System**
 - [x] This PR is for the `develop` branch not the `master` branch
 - [ ] I've updated the changelog
 - [x] This PR is complete and ready for review

### CODE REVIEW

**Comment by Mte90** [comment]
it is missing shellcheck for bash stuff.

**Comment by tomjn** [comment]
Indeed, those actions didn't work, it can be added in another PR

**Comment by Mte90** [comment]
So you need an approval for this pr? there is a way to test those workflow?

**Comment by tomjn** [comment]
> So you need an approval for this pr? there is a way to test those workflow?

All PRs need approval, merging without approval is for admins when we need emergency fixes. The PR tests itself, see the checks that passed

**Pull request merged**
