### PR TITLE
provision tools via composer

### PR DESCRIPTION
**Pull request by cfoellmann**
It _should_ be easy to speed up the provision process by using composer over git checkouts.
My composer setup in this PR works but I can not get the nginx aliases to work. 

__Anyone have an idea?__

The aliases would keep the current url structure for the vvv.dev vhost

__________________
Implements #574

### CODE REVIEW

**Comment by jeremyfelt** [comment]
One reason we use the git clone of wp-cli is to provide an easy way to contribute there as well. We should probably leave that as is.

I thought the same thing about the WordPress code standards sniffer, but that may not be the case. @westonruter?

Otherwise, for things like PHPMyAdmin, this would definitely be an improvement as far as maintainability goes.

**Comment by westonruter** [comment]
I definitely would encourage the WordPress Coding Standards repo to be distributed as a git clone as well to facilitate contributing.

**Comment by cfoellmann** [comment]
I am totally with you. Was thinking the same after I sent the pr.
Will revert WP-cli and cs

**Comment by cfoellmann** [comment]
at the current state the aliases work but no php is processed.
Anyone have an idea how to fix the aliased folders to process the .php files?

**Comment by jeremyfelt** [comment]
@cfoellmann Sorry to leave you hanging so long. :) Do you want a feature branch to merge this into for testing?

**Comment by cfoellmann** [comment]
Any idea how to get php working for the provisioned tools?

**Comment by cfoellmann** [comment]
can someone _PLEASE_ fix the vhost aliases?
I am about to abandon VVV because nginx is just fucking stupig (or I am).

**Comment by cfoellmann** [comment]
Currently the aliases work for .php files and for these only

**Comment by cfoellmann** [comment]
@jeremyfelt please add `in progress` label

**Comment by cfoellmann** [comment]
Will close this for now.
The destination branch is wrong + I need to revisit this topic when I got some free time again.

**Pull request closed without merging**
