### PR TITLE
Modify/better php debug switcher

### PR DESCRIPTION
**Pull request by tomjn**
This greatly improves the `switch_php_debugmod` script so that:

 - it no longer tries to disable modules that are already disabled
 - it no longer tries to enabel modules that are not installed
 - it enables/disables modules on a per PHP basis to avoid warnings when a module does not support all installed versions ( e.g. pcov did not support 7.0 and below, and would generating warnings if those were installed )
 - improves output so it's clearer to users what's happening and which versions of PHP a debug module is active on

## Checks

* [ ] I've updated the changelog.
* [ ] I've tested this PR
* [ ] This PR is for the `develop` branch not the `stable` branch.
* [ ] This PR is complete and ready for review.

### CODE REVIEW

**Comment by tomjn** [comment]
Screenshot 2021-03-05 at 17 40 53

**Comment by tomjn** [comment]
Do you have PHP 8.0 setup right? `conf.d` should exist

**Comment by Mte90** [comment]
No my VVV instance doesn't have php 8. Just 71/72/73.

**Comment by tomjn** [comment]
That'll be why then, does `/etc/php/8.0/` exist?

**Pull request merged**
