### PR TITLE
Expand the composer installation steps output and checks

### PR DESCRIPTION
**Pull request by tomjn**
## Checks

* [ ] I've updated the changelog.
* [ ] I've tested this PR
* [ ] This PR is for the `develop` branch not the `stable` branch.
* [ ] This PR is complete and ready for review.

### CODE REVIEW

**Comment by tomjn** [comment]
So the downloading of WP CLI is failing sometimes for unknown reasons but succeeding other times. Curl exit code of 3 which implies a malformed request.

I think to get more useful data it might be best to run the command without the silencing option in a sub-shell and inspect the exit code via `$?` then print out the results if it failed so we can see what curl said.

**Comment by tomjn** [comment]
so `npm` being missing after grunts installation is frustrating and difficult to explain

**Comment by tomjn** [comment]
Todo list:

 - figure out how to make the parallelised hooks exit on failure and acknowledge bad return codes
 - I think npm issue can be resolved by switching the node provisioner to nvm, it's been a long time coming
 
For now this PR disabled parallelised tools provisioners to get around the first bullet point, I believe the second bullet point already impacts the main branch, so I vote to merge once changelogs are updated

**Review by Mte90 — APPROVED** [review]

**Comment by Mte90** [comment]
We need a ticket to track this other things to do but about the rest ok

**Pull request merged**
