### PR TITLE
Automated testing

### PR DESCRIPTION
**Pull request by miya0001**
Add automated testing using serverspec.
http://serverspec.org/
### How to run automated testing

```
$ bundle install
$ rake spec
```

### CODE REVIEW

**Comment by jeremyfelt** [comment]
Poking at this a bit more finally. :)

I like the idea of having tests included, that seems really approachable. It would also be nice to figure out how to apply CI to this, though that seems like a longer trail.

Travis CI, [from what I gather](http://omerkatz.com/blog/2013/6/15/travis-ci-does-not-work-when-you-package-vagrant-boxes-as-a-build-step-yet), doesn't support Vagrant because Vagrant doesn't support OpenVZ. Even if Vagrant did support OpenVZ (which this [plugin](https://github.com/abrooke/vagrant-openvz) may provide), the results of provisioning may differ quite a bit from our default provisioning targeted to VirtualBox.

[This post](http://spry-group.com/blog/Vagrant-in-my-CI-pipeline/) implies that it's pretty straight forward with Jenkins. The caveats being (1) a base, mostly provisioned box would be necessary to reduce build time and (2) we would need to have our own Jenkins configuration.

Fun stuff. :)

**Comment by miya0001** [comment]
Some projects are running `vagrant up` with option `--provider=aws` for CI to it.
I am thinking about trying to it.

Example:
```
language: ruby
rvm:
- 2.0.0
install:
- wget https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.2_x86_64.deb
- sudo dpkg -i vagrant_1.7.2_x86_64.deb
before_script:
- vagrant plugin install vagrant-aws
- vagrant up --provider=aws
script:
- bundle install
- bundle exec rake
after_script:
- vagrant destroy -f
env:
  global:
  - secure: abcdefghijk
  - secure: 012345678
```
https://github.com/winebarrel/cronicle/blob/master/.travis.yml

**Comment by miya0001** [comment]
@jeremyfelt 

I tried running tests on Travis CI.
I got some errors but works as expected.

https://travis-ci.org/miya0001/VVV

We need to improve tests. :)

**Comment by miya0001** [comment]
I got `passed`!!
https://travis-ci.org/miya0001/VVV/builds/63479015

```
Cleaning the virtual machine's /etc/hosts file...
Adding domains to the virtual machine's /etc/hosts file...
 * Added vvv.dev from /srv/www/vvv-hosts
 * Added local.wordpress.dev from /srv/www/vvv-hosts
 * Added local.wordpress-trunk.dev from /srv/www/vvv-hosts
 * Added src.wordpress-develop.dev from /srv/www/vvv-hosts
 * Added build.wordpress-develop.dev from /srv/www/vvv-hosts
-----------------------------
Provisioning complete in 382 seconds
External network connection established, packages up to date.
For further setup instructions, visit http://vvv.dev
$ bundle exec rake spec
/home/travis/.rvm/rubies/ruby-1.9.3-p551/bin/ruby -I/home/travis/build/miya0001/VVV/vendor/bundle/ruby/1.9.1/gems/rspec-core-3.2.3/lib:/home/travis/build/miya0001/VVV/vendor/bundle/ruby/1.9.1/gems/rspec-support-3.2.2/lib /home/travis/build/miya0001/VVV/vendor/bundle/ruby/1.9.1/gems/rspec-core-3.2.3/exe/rspec --pattern spec/default/\*_spec.rb

File "/etc/php5/fpm/conf.d/php-custom.ini"
  should be file
  should contain /short_open_tag = Off/
  should contain /allow_call_time_pass_reference = Off/
  should contain /max_execution_time = 30/
  should contain /memory_limit = 128M/
  should contain /error_reporting = E_ALL | E_STRICT/
  should contain /display_errors = On/
  should contain /log_errors = On/
  should contain /log_errors_max_len = 1024/
  should contain /ignore_repeated_errors = Off/
  should contain /ignore_repeated_source = Off/
  should contain /track_errors = Off/
  should contain /html_errors = 1/
  should contain /error_log = \/srv\/log\/php_errors.log/
  should contain /post_max_size = 50M/
  should contain /upload_max_filesize = 50M/
  should contain /max_file_uploads = 20/
  should contain /default_socket_timeout = 60/

Host "vvv.dev"
  should be resolvable

Host "local.wordpress.dev"
  should be resolvable

Host "local.wordpress-trunk.dev"
  should be resolvable

Host "src.wordpress-develop.dev"
  should be resolvable

Host "build.wordpress-develop.dev"
  should be resolvable

Service "nginx"
  should be enabled
  should be running

Service "mysql"
  should be enabled
  should be running

Service "php5-fpm"
  should be enabled
  should be running

Port "80"
  should be listening

Port "443"
  should be listening

Command "wget -q http://local.wordpress.dev/ -O -"
  stdout
    should match /WordPress/

Command "wget -q http://local.wordpress-trunk.dev/ -O -"
  stdout
    should match /WordPress/

Command "wget -q http://src.wordpress-develop.dev/ -O -"
  stdout
    should match /WordPress/

Command "wget -q http://build.wordpress-develop.dev/ -O -"
  stdout
    should match /WordPress/

Command "wp --info"
  exit_status
    should eq 0

Command "phpunit --version"
  exit_status
    should eq 0

Command "git --version"
  exit_status
    should eq 0

Command "dos2unix --version"
  exit_status
    should eq 0

Command "ngrep -V"
  exit_status
    should eq 0

Command "composer --version"
  exit_status
    should eq 0

Command "grunt --version"
  exit_status
    should eq 0

Command "wget -q http://vvv.dev/ -O - | grep '<title>'"
  stdout
    should match /<title>Varying Vagrant Vagrants Dashboard<\/title>/

Command "wget -q http://vvv.dev/database-admin/ -O - | grep '<title>'"
  stdout
    should match /<title>phpMyAdmin<\/title>/

Command "wget -q http://vvv.dev/memcached-admin/ -O - | grep '<title>'"
  stdout
    should match /<title>phpMemcachedAdmin .*<\/title>/

Command "wget -q http://vvv.dev/opcache-status/opcache.php -O - | grep '<title>'"
  stdout
    should match /<title>PHP .* with OpCache .*<\/title>/

Command "wget -q http://vvv.dev/webgrind/ -O - | grep '<title>'"
  stdout
    should match /<title>webgrind<\/title>/

Command "wget -q http://vvv.dev/phpinfo/ -O - | grep '<title>'"
  stdout
    should match /<title>phpinfo\(\)<\/title>/

Finished in 11.25 seconds (files took 0.75069 seconds to load)
48 examples, 0 failures


The command "bundle exec rake spec" exited with 0.

Done. Your build exited with 0.
```

**Comment by jeremyfelt** [comment]
@miya0001 Thank you for all of your effort on this pull request! It's a great example of what's possible.

I'm not sure Serverspec is the right answer now, though it certainly may be one day. After chatting with @LoreleiAurora, I'm starting to understand how we may be able to use a server hosted on Digital Ocean or EC2 to help build and test machines on the fly. It's very possible that we'll be able to reference this at some point.

**Comment by miya0001** [comment]
> I'm starting to understand how we may be able to use a server hosted on Digital Ocean or EC2 to help build and test machines on the fly.

Nice! 😄

**Pull request closed without merging**
