### PR TITLE
Add hosts for hostsupdater plugin

### PR DESCRIPTION
**Pull request by kkatano**

### CODE REVIEW

**Comment by JJJ** [comment]
Hey @kkatano. I think I understand what problem you're hoping to solve, but I think there this isn't going to be the correct approach in the long term.

A few things this misses:

* The multisite repos
* The WordPress.org meta sites
* Custom websites

For this to be complete, will require the hosts updater to be more aware of what sites are enabled, which I'm pretty sure my VVV checkouts have always done a pretty good job at doing already.

Can you explain more about why you think this change is necessary? Maybe I can help test this or other solutions.

**Comment by LoreleiAurora** [comment]
@kkatano @JJJ This is something ive neglected to add to the new config file, will fix this over the next 24 hours.

**Comment by LoreleiAurora** [comment]
@kkatano @JJJ The VVV hosts files have moved into the individual site dirs and are available after the first provision, therefore you just have to reprovision. Im trying to think of a better way to deal with this.

**Comment by kkatano** [comment]
@JJJ @LoreleiAurora 
Thanks, i see.
I tried re-provision and got fine result.

**Pull request closed without merging**
