### PR TITLE
Dashboard Improvements

### PR DESCRIPTION
**Pull request by tomjn**
**edit:** I made more changes to the dashboard, scroll down

----

If a site fails to provision it will load the vvv.dev dashboard with no warning

So lets add one :)

screen shot 2017-09-13 at 09 46 20

It checks to see if the URLs domain is vvv.dev and if it isn't, then it unhides a warning at the top with some information and a link to the troubleshooting page

If someone can indicate how to know in PHP if the VM is still provisioning then I can add a yellow banner instead indicating that provisioning is ongoing and to check back in a bit

### CODE REVIEW

**Comment by cfoellmann** [comment]
I am pretty sure that you won't get anything rendered with a failed provision.
If the Webserver is not working it won't be able to output a warning or error

**Comment by tomjn** [comment]
Not at all, for example I'm using this in `vvv-custom.yml` to test this:

```
  bananas:
    repo: https://lacookaracha.com
    skip_provisioning: false
    hosts:
      - bananas.dev
```

Visiting `bananas.dev` results in the provision error, as Nginx is working fine, but that specific site failed to provision show Nginx doesn't know about it and shows the default, which is the dashboard

**Comment by tomjn** [comment]
I've expanded the dashboard with some documentation and styling, and turned some links into buttons. I also added an example of adding a site and a link to full documentation, and a prompt to the VVV 1 migration docs:

screen shot 2017-09-13 at 16 01 26

**Comment by cfoellmann** [comment]
I like it and I see what the purpose of the error is now.
I thought you wanted to show the error on a broken provisioning of the "server software"

**Comment by tomjn** [comment]
heh I wish I could, but in the meantime, I've made a lot more changes

Adding a new site:

screen shot 2017-09-14 at 09 28 38

When the PR for the docs theme change is merged we'll have search, so I set up a search box, it's commented out for now but the styling etc is all there:

screen shot 2017-09-14 at 14 01 49

I added a YAML parser and replaced the list of bundled sites with a dynamic list that pulls from `vvv-custom.yml`:

screen shot 2017-09-14 at 15 45 22
screen shot 2017-09-14 at 16 08 03
screen shot 2017-09-14 at 16 13 25


The full dashboard currently looks like this:

screen shot 2017-09-14 at 16 14 16

I'm currently toying with a block for contributing to WP similar to the adding a site that explains how to add the meta environment briefly with a link to a doc, it may be a sidebar block with just a button though as I don't want to add a lot of documentation directly to the dashboard

**Comment by tomjn** [comment]
Disabled/skipped sites now show up faded out

screen shot 2017-09-14 at 16 22 38

**Comment by tomjn** [comment]
Now with contributor day and WP CLI prompts

screen shot 2017-09-14 at 16 38 06

**Comment by cfoellmann** [comment]
I like what you are doing but it seems too much. If I am an experienced user I dont want to see about half of that.
I suggest putting everything below "sites" and "tools". Maybe you can use an anchor link to scroll down to the help stuff

**Comment by tomjn** [comment]
You mean shove it under the fold? But then how will new users who need those prompts find them if they're hidden away?

Fundamentally, the dashboard can be overridden by copying it to `custom.php` and removing the parts you don't like, and since we can't personally customize I believe it important to address feedback given out in the field from people who've struggled or misunderstood. I've encountered people who've struggled with YAML, or expected a full site list, users who didn't realise you had to re-provision on change, or community deputies who've handed me their machines because it's complicated and they need a meta environment right now with no time to learn.

With that feedback in mind, the default dashboard should avoid any misunderstandings and try to improve the experience for the majority of users. I understand a spartan dashboard with the bare essentials can be a desirable thing, but that is still possibility.

**Comment by tomjn** [comment]
This is what the current build looks like:

screen shot 2017-09-18 at 18 34 36

As far as I'm concerned it's ready for testing and review

**Pull request merged**
