### PR TITLE
Mailhog

### PR DESCRIPTION
**Pull request by tomjn**
related to https://github.com/Varying-Vagrant-Vagrants/vvv-utilities/pull/17

Attempts to install golang and setup MailHog, serving it at http://vvv.test:8025

TODO: 
 - Setup auto startup on vagrant up
 - Make the dashboard detect if mailhog is present and add a MailHog button, remove the mailcatcher button
 - test test test test

I'd advise waiting until the utilities PR has been merged to test

### CODE REVIEW

**Comment by Mte90** [comment]
Just for test:

* to use https://github.com/Varying-Vagrant-Vagrants/vvv-utilities/pull/17/files change in your vvv-custom.yml `utility-sources` and add `branch: mailhog`
* go to vvv folder and `git pull & git checkout mailhog`
* do a `vagrant provosion`

From what I can see https://packages.ubuntu.com/trusty/golang-go for ubuntu 14 go is available.

**Comment by tomjn** [comment]
That's true and it's what I used initially, but the version is older and
mailhog fails to build when using it

**Comment by tomjn** [comment]
For reference I've been following this: https://www.lullabot.com/articles/installing-mailhog-for-ubuntu-1604

Though I've deliberatley left out the IPs so that it uses the default `0.0.0.0`, setting just the web interface so it had the same port as mailcatcher caused issues with websocket connections. I did get it to catch via `mhsendmail`, and I pushed up a branch to VVV utilities that adjusts PHP

I still need to make it start on startup automatically though, something that was also broken in mailcatcher, but I've not implemented the steps to do so yet, so it should run after a `vagrant up --provision` but not a `vagrant up`

**Comment by tomjn** [comment]
For reference, this PR won't fully provision anyway since when it starts mailhog it blocks provisioning continuing

**Comment by Mte90** [comment]
Let me know when it's time to test :-D

**Comment by dingo-d** [comment]
@tomjn Is the provisioning passing for you? I get errors when I try to provision

>dpkg: dependency problems prevent configuration of php7.2-dev:
    default:  php7.2-dev depends on php7.2-cli (>= 7.2.7-1+ubuntu14.04.1+deb.sury.org+1); however:
    default:   Package php7.2-cli is not configured yet. (--configure):
    default: dpkg: error processing package php7.2-dev (--configure):error exit status 2
    default:  dependency problems - leaving unconfigured1+deb.sury.org+1) ...
    default: dpkg: dependency problems prevent configuration of php7.2-fpm:
    default:  php7.2-fpm depends on php7.2-cli; however:
    default:   Package php7.2-cli is not configured yet.
    default: dpkg: error processing package php7.2-fpm (--configure):
    default:  dependency problems - leaving unconfigured
    default: No apport report written because the error message indicates its a followup error from a previous failure.
    default: No apport report written because MaxReports is reached already
    default: Errors were encountered while processing:
    default:  install-info
    default:  php7.2-cli
    default:  php7.2-dev
    default:  php7.2-fpm
    default: E: Sub-process /usr/bin/dpkg returned an error code (1)
    default: Main packages check and install failed, halting provision

**Comment by tomjn** [comment]
PHP 7.2 issues should be unrelated to this, this PR does not touch PHP, that is an unknown error

Note that with b176a02 MailHog runs for me, there's still clean up to do:

 - mailcatcher seems to prevent mailhog from running if it too is running, we need a mechanism to uninstall it
 - right now it tries to stop the mailcatcher service and remove the service file, even if they don't exist, which is sloppy
 - Mailhog is available at `vvv.test:8025` the dashboard should be updated to reflect this

**Comment by tomjn** [comment]
I believe it's testing time

**Comment by Mte90** [comment]
Wow I can confirm that works!

**Comment by tomjn** [comment]
Can you post a screenshot showing it catching mails? It'd be handy for the 2.3 release

Additionally, any thoughts on uninstalling mailcatcher?

**Comment by Mte90** [comment]
I made a screen that show in Firefox the permission to sent notifications, but I saw later that is in Italian. I hope that is not a problem.
screenshot_20180626_154405

For mailcatcher we can do that when is set mailhog is checked the mailcatcher folder and is removed everything about it.

**Comment by tomjn** [comment]
Awesome, then I think all that's left is to approve and merge, we can optimise mailcatcher cleanup later

**Comment by Mte90** [comment]
I think too and the feature of browser notification is very handy, you have only to remember to press connect that is not made automatically, for the rest is very cool.

**Pull request merged**
