### PR TITLE
[PR] Add libssh2-1-dev and libssh2-php modules

### LINKED ISSUE #801: Add ssh php module
For fix a ticket in WordPress core I had the support for that.
So I've followed that guide to install the module http://www.asim.pk/2010/05/27/installing-phps-ssh2-extension-on-ubuntu/.
Maybe add that package in the provision simplify for others that problem.

### PR DESCRIPTION
**Pull request by Mte90**

### CODE REVIEW

**Comment by Mte90** [comment]
any news for that pr?

**Comment by jeremyfelt** [comment]
Hi @Mte90 - It looks like there is a merge conflict due to the change in the contributors list. Can you refresh the pull request to just add the packages? We can take care of adding you to the contributors list in a separate commit. It'd probably be good to test with PHP7 as well now that that's in. :smile: 

Thanks!

**Comment by Mte90** [comment]
As I can see ubuntu don't have the package and we need to compile: https://www.ikq.me/2016/01/12-steps-to-install-libssh2-for-php7/

**Comment by jeremyfelt** [comment]
Thanks for the pull request, @mte90. I'm going to close this out as we'll need a different solution for PHP 7.0. I've opened #923 to start a discussion.

**Pull request closed without merging**
