### PR TITLE
Add/site composer

### PR DESCRIPTION
**Pull request by tomjn**
This extends the folders `config.yml` feature to allow a subset of `composer` commands

## Checks

* [x] I've updated the changelog.
* [ ] I've tested this PR
* [x] This PR is for the `develop` branch not the `stable` branch.
* [ ] This PR is complete and ready for review.

### CODE REVIEW

**Comment by tomjn** [comment]
In theory, this site will clone Laps into a folder then run composer install in said folder:

```yaml
  laps:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - laps.test
    folders:
      public_html/wp-content/plugins/laps:
        git:
          repo: https://github.com/Rarst/laps.git
        composer:
          install: true
```

**Comment by Mte90** [comment]
Just a reminder for the future we need to add some docs and also something in the example file.

**Comment by tomjn** [comment]
`npm` support added, and refactored things to warn on unknown keys, and execute in the order they're listed

**Comment by Mte90** [comment]
Can you add also an example for npm just for documentation and help with testing when will be the day to do it?

**Comment by Mte90** [comment]
Ping so with a bit of docs I can do some testings

**Comment by tomjn** [comment]
@Mte90 docs aren't a part of this PR, they go on a separate repo. For how to test, we already have a test case in this comment https://github.com/Varying-Vagrant-Vagrants/VVV/pull/2331#issuecomment-752083183, any docs written wouldn't reveal anything already shared in this PR

**Comment by Mte90** [comment]
I have errors on running this pr:

```
[0m[39m[2m * Downgrading to Node v10.[21m[0m

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
The following packages will be REMOVED:
  nodejs
0 upgraded, 0 newly installed, 1 to remove and 51 not upgraded.
After this operation, 119 MB disk space will be freed.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 107299 files and directories currently installed.)
Removing nodejs (14.15.5-1nodesource1) ...
dpkg: warning: while removing nodejs, directory '/usr/lib/node_modules' not empty so not removed
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package install
```

**Comment by Mte90** [comment]
It was a bug in VVV that one not this pr.

**Pull request merged**
