### PR TITLE
Fixes #2048 and improves log messages

### LINKED ISSUE #2048: Vagrant send email from inside box to outside world
This is a weird problem that I also don't fully understand.

Last week I set up a new site synced the database and reset all users (a couple 1000) passwords to _123_.  It makes testing easy, it's a thing I've been doing for at least a year. Never a problem, including for this site.

But this time we were getting a few support emails from people saying the password was reset.
**Some way emails send in the vagrant where arriving out in world.**

Example email headers I got in support:

The rest of the day was cleaning up after this, and trying a few things. It was _not_ a fun day, to keep it professional.....

Details
-------------

- I destroyed the box, pretty much immediately to make sure there wasn't some invisible queue.
- There was no SMTP used, it was vvv.
- I have not been able to get an other real email out into the world after this incident.
- There is no record how many emails have been send.
- Most likely it was just a vanilla box V3.2.0, I'm like 90% sure.
- I am 100% sure I've never (un)installed/tweaked anything regarding mailhog/email/ect inside the box.

The core of the script I ran was pretty much this:  
wp-cli:  `wp eval-file  reset-password.php` >>

		$userQ = new \WP_User_Query(array());
		foreach ( $userQ->get_results() as $user ) {
			$user->user_pass = '123';
			wp_update_user( $user );
		}

Steps to reproduce
------------------------
This will not send out a real email into the world. But will bypass mailhog.
I think this is the main issue to fix.

1 create a fully new vagrant, everything default
2. login in one.wordpress.test/wp-admin
3. create new user
4. check mailhog, success
5. `vagrant ssh `
6. `cd /srv/www/wordpress-one/public_html/`
7. `wp user create test2 me+test2@janw.me --send-email`
8. check mailhog, no email

Some command I found out while trying to debug this.

 - `sudo cat /var/log/mail.log`
 - `sudo mailq`
 - `cat /var/mail/vagrant` This shuld be the email itself

This problem exists in [develop](https://github.com/Varying-Vagrant-Vagrants/VVV/commit/985cb6b7042206b4bfc6be1f9cd5aa595203ca73) and [master](https://github.com/Varying-Vagrant-Vagrants/VVV/commit/d0eeb9f55919f8112f4355363148ae43915fae65) but not [3.1.0](https://github.com/Varying-Vagrant-Vagrants/VVV/commit/c727e91c4c5c3ec86db80a11ec1571a085f83854) and [3.0.0](https://github.com/Varying-Vagrant-Vagrants/VVV/commit/c9d33ff5a7831432d4988f981548d7fbd8c27734) 

Requested solution
-------------------------

Make wp-cli/commands send email to mailhog again

If there is anything I can do to help let me know.

### PR DESCRIPTION
**Pull request by tomjn**
## Summary:

Activates MailHog for PHP CLI, and improves some logging

## Checks

* [ ] I've tested this PR with Vagrant **vXX** and VirtualBox **vXX** on **Operating System**
* [x] This PR is for the `develop` branch not the `master` branch.
* [ ] I've updated the changelog.
* [ ] This PR is complete and ready for review.

### CODE REVIEW

**Comment by tomjn** [comment]
I'm pretty sure this resolves the problem, not sure why MailHog was setup only for FPM to begin with, might be a copy paste from when it was first added or a historical oversight.

To get merged I'd like to see somebody else confirm this is working, the check that `mhsendmail` is in the PHP ini on CLI rather than `sendmail` will suffice:

```shell
php -i | grep sendmail_path
```

https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2048#issuecomment-576254669

**Comment by Mte90** [comment]
In my instance is already:
```
vagrant@vvv:~$ php -i | grep sendmail_path
sendmail_path => /usr/local/bin/mhsendmail => /usr/local/bin/mhsendmail
```

So we need that someone with the issue can test it, I don't know why on my instance is already fixed also without this pr.

**Comment by tomjn** [comment]
@Mte90 so was mine, I had to provision a fresh install to reproduce

**Comment by tomjn** [comment]
It appears this commit is what introduced the issue:

https://github.com/Varying-Vagrant-Vagrants/VVV/commit/a11ae203ab42ad5b55a6bf41c46f9734d3c7edf1

Perhaps this PR then reintroduces an older bug, I wonder if it should actually be:

```sh
phpenmod -s ALL mailhog
```

**Comment by Mte90** [comment]
Maybe we can do some tests with this command on new instance and old ones.

**Comment by Mte90** [comment]
> It appears this commit is what introduced the issue:
> 
> [a11ae20](https://github.com/Varying-Vagrant-Vagrants/VVV/commit/a11ae203ab42ad5b55a6bf41c46f9734d3c7edf1)
> 
> Perhaps this PR then reintroduces an older bug, I wonder if it should actually be:
> 
> ```shell
> phpenmod -s ALL mailhog
> ```

I tested on a new machine, this works the path of mailhog is changed on cli too.

**Pull request merged**
