### PR TITLE
Switch to php 8.2 as the default

### PR DESCRIPTION
**Pull request by tomjn**
Switch to 8.2 as the default PHP, 8.0 is no longer supported, 8.1 is security fixes only, and 8.3 is brand new, so 8.2 it is!

If people need 8.0 or other versions they can use the core extensions

## Checks

* [x] I've updated the changelog.
* [x] I've tested this PR
* [x] This PR is for the `develop` branch not the `stable` branch.
* [x] This PR is complete and ready for review.

### CODE REVIEW

**Comment by tomjn** [comment]
Also noting that a number of hosts are skipping 8.1 as an option, e.g. WP Engine, and VIP is on 8.2

**Review by Mte90 — DISMISSED** [review]

**Comment by tomjn** [comment]
Checks failed, missed an 8.0 in the site provisioner

**Comment by Mte90** [comment]
There is still something using php 8.0

**Comment by tomjn** [comment]
Ended up needing some fixes in the site template to avoid a `sed` issue in docker

**Pull request merged**
