### PR TITLE
Added git lfs support

### PR DESCRIPTION
**Pull request by obilodeau**
`git lfs` is very useful in web design environments where a lot of large `.psd`, `.jpg`, etc. files are thrown around. It makes git a lot faster with files it has no chance of optimizing due to their high compression.

It is not a complex or long install but the key current pgp key I used will expire in 2019 so be aware of that.

Need #1567 fixed before it can work.

### CODE REVIEW

**Comment by tomjn** [comment]
@obilodeau This looks good, needs testing though, is there a repo with git LFS that we can use for reference?

**Comment by obilodeau** [comment]
> This looks good, needs testing though, is there a repo with git LFS that we can use for reference?

I tested it but I agree that this needs to be tested by someone else.

I added a site in `vvv-custom.yml` with the following definition:
```yaml
  mysite:
    repo: https://github.com/Apress/repo-with-large-file-storage.git
    hosts:
      - git-lfs.test
```

and inspected the files manually using `vagrant ssh` and git lfs did its job.

**Comment by tomjn** [comment]
Apologies for the delay in testing, this slipped my mind

**Comment by tomjn** [comment]
@obilodeau I gave this a go and it checked out the repo but the large file zip is just a text file placeholder:

```
version https://git-lfs.github.com/spec/v1
oid sha256:6e1b890dafa9956b1bdff43b3fd46aaf273085a1d2041bde7efce6cf5eb0262b
size 207809687
```

It doesn't look like this was succesful, or at least not after a `vagrant halt; vagrant up --provision`

**Comment by tomjn** [comment]
This works! The only caveat is that if a git repo has already been created, it won't retroactively fix LFS files

**Pull request merged**
