### PR TITLE
change ownership from root to vagrant for /vagrant

### PR DESCRIPTION
**Pull request by benlumia007**
## Checks

 - [x] I've tested this PR with Vagrant **2.2.4** and VirtualBox **6.0.8** on **LInux**
 - [x] This PR is for the `develop` branch not the `master` branch
 - [x] I've updated the changelog
 - [x] This PR is complete and ready for review
 
 

The ownership should be now be `vagrant`
`drwxr-xr-x   2 vagrant vagrant  4096 Jun 29 22:15 vagrant`

### CODE REVIEW

**Comment by paulschreiber** [comment]
`sudo chown -R vagrant:vagrant /vagrant` is a partial fix. you also need chmod a+r vvv-custom.yml (or similar.

**Comment by benlumia007** [comment]
I don't think it matters, the user edits the vvv-custom.yml file from their own computer and it gets copy to the vm home directory and copies again to the /vagrant folder then it only gets read and passs so that the dashboard can get the information from.

**Comment by paulschreiber** [comment]
Again, the webserver needs to be able to read the vvv-custom.yml file to render https://vvv.test. See #1886.

**Comment by tomjn** [comment]
@benlumia007 the config file gets read by the provisioners and the VVV dashboard, so it needs to be readable

**Comment by benlumia007** [comment]
even if it gets read, it wouldn't matter much, you aren't really editing the file when you vagrant up after you finish editing the file so that it creates the site, this is more about the root and /vagrant folder that is contained files inside. even if it was under root or vagrant, is still readable, isn't. if it wasn't readable, then everyone would have problems loading sites and the dashboard. 

The last comment i posted, i never said that the file doesn't get read, i pretty sure i said, it gets read so that the dashbarod can get the information or anything that gets used by shyaml.

**Comment by benlumia007** [comment]
the /vagrant folder only contains the vvv-custom.yml, provisioning_at and version,  it does not contain any sites files/folders for that matter, the www is own by vagrant:www-data,  the /vagrant can be own by root or vagrant because its readable depends on which user is been used to create the /vagrant folder.

**Comment by benlumia007** [comment]
The web server has nothing to do with the vvv-custom.yml file,  the web server is just allows you to run web service. the vvv-custom.yml is just a file that gets used by `shyaml` to gain access to the vvv-custom.yml and process it and generates a site or feature that is contained in the file.

**Pull request merged**
