### PR TITLE
fix #2150 dpkg frontend lock

### LINKED ISSUE #2150: Unable to acquire the dpkg frontend lock
## What was The Command Used To Provision

vagrant up --provision

## What Kind of VVV Provision Was This

This was a reprovision of an already working VVV

## Steps to Reproduce (for bugs)
1.   The issue seems to happen each morning, after a fresh boot of the system (iMac)
2.  If the system has been running for 30mins+ and I run a Vagrant Up, it usually works fine.
3.  Have previously tried a clear-out of VVV, Vagrant & VB & re-install (around time of 3.2.0 relase)
4. 

Linked above

## Your Environment

Linked above

### PR DESCRIPTION
**Pull request by Mte90**
## Summary:
fix https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2150

### CODE REVIEW

**Comment by msaggiorato** [comment]
What's the condition that #2150 happens on? Seems like a failed provisioner right? Or a machine that was force halted during the install process.

If that is the case, should we be removing the locks? Or forcing the user to force recreate the machine, just to avoid any potential problems with failed provisions.

**Comment by Mte90** [comment]
I think that is a provisioner fail previously but is the only way to fix it is to remove the file. On my debian system I do the same.

**Comment by macgraphic** [comment]
I added the line to provision.sh
`  # fix https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2150
  rm /var/lib/dpkg/lock*`

But I am still getting the same error on a 'vagrant up --provision'
`    default:  * Installing apt-get packages...
    default: E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)
    default: E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
    default:  * Installing apt-get packages returned a failure code, cleaning up apt caches then exiting`

To correct or to start VVV, I then run `vagrant reload --provision`

**Comment by Mte90** [comment]
I tested now the pr (because I had that problem) and worked.
Did you added that line to the right line? Are you using the develop branch or switched to the pr one?

**Comment by tomjn** [comment]
Is there an `apt` or `dpkg` based way of clearing it? Removing the file works but if there's a better way, similar to how you can run `svn cleanup` then that might help avoid any strange issues encountered

**Comment by tomjn** [comment]
Also can we get a changelog update?

**Comment by Mte90** [comment]
Changelog updated and no there isn't any way.
Remove that files is the only way to fix it with apt (debian user talking), the lock files are crate by linux processes but they are not removed if the process itself is killed (like libreoffice or vim) so you have to remove it manually.

**Pull request merged**
