### PR TITLE
Add/box scripts

### PR DESCRIPTION
**Pull request by tomjn**
## Summary:

Adds the 2 box minimizing scripts to the homebin folder. This should assist with https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2139

### CODE REVIEW

**Comment by Mte90** [comment]
Documentation for this?

**Comment by tomjn** [comment]
This isn’t something I want end users to use, these are the vagrant box
minimising scripts aka magically make the final file smaller. They do what
they say on the tin

**Comment by msaggiorato** [comment]
If people shouldn't be using this, shouldn't this be on the USB Generator somehow?

**Comment by tomjn** [comment]
> If people shouldn't be using this, shouldn't this be on the USB Generator somehow?

sure but then what if I wanted to make a box for other reasons? Now it's here, and it's in the USB generator, and it's in the box builder repo, so many duplicated copies all over the place. You get a copy of the script, and you get a copy of the script, and every repo gets a copy of the script, and so many copies...

Or we can put it here and have 1 place for the script.

**These scripts make adjustments to the VM so that when it's boxed up it makes a smaller file.**

The messages are for people who might think it's for other things, like making their VM smaller, or they might run these scripts because they want to keep their VM clean. All of which are bad ideas. That's why these scripts won't be documented on the docs site. The only docs they need are the changelog, otherwise these are for internal use.

**Pull request merged**
