### PR TITLE
fix 'stdin: is not a tty'

### PR DESCRIPTION
**Pull request by cfoellmann**
Needs testing!! Works for me so far.

Needs a description but I dont know what to write other than 'fixes `stdin: is not a tty`'
props @artemkaint

SEE: https://github.com/Varying-Vagrant-Vagrants/VVV/issues/229#issuecomment-76149619

### CODE REVIEW

**Comment by artemkaint** [comment]
I found small problem with this fix. 
vagrant ssh -c 'some command' does not work

Now I am using 
<pre><code>config.ssh.shell = "bash" </code></pre>
and in provision 
<pre><code>export DEBIAN_FRONTEND=noninteractive </code></pre>
for fix "dpkg-preconfigure: unable to re-open stdin: No such file or directory"

**Comment by cfoellmann** [comment]
Thanks for testing.
It is some deeper vagrant issue

**Comment by cfoellmann** [comment]
Maybe @artemkaint can pitch in on this !?
What do you say? What is your experience?

**Comment by jcart** [comment]
Why was this closed? What is the resolution?

**Comment by cfoellmann** [comment]
@jrb this solution doesn't work correctly.
have a look at #633

**Comment by zamoose** [comment]
@cfoellmann:
It works perfectly over on HGV for us. What do you mean, "doesn't work"?

**Comment by cfoellmann** [comment]
This fix screws with `vagrant ssh`

**Comment by zamoose** [comment]
In what way? Again -- it works perfectly for HGV. The fix given in the other ticket doesn't work during the first provisioning, IIRC.

**Comment by zamoose** [comment]
Ahh, @cfoellmann I see what you mean -- it breaks `vagrant ssh -c [command]`. `vagrant ssh` continues to work correctly, but you cannot send arbitrary commands to the VM with `-c` with that fix.

**Comment by cfoellmann** [comment]
How is #633 working for you?

**Pull request closed without merging**
