### PR TITLE
Add default CPU cores

### PR DESCRIPTION
**Pull request by hubdotcom**
As per documentation:
http://docs.vagrantup.com/v2/virtualbox/configuration.html
http://parallels.github.io/vagrant-parallels/docs/configuration.html

### CODE REVIEW

**Comment by cfoellmann** [comment]
I am not sure if we "can"/want to go with 2 cores. Some machines might be too weak to support the VM and proper performance for the host

**Comment by hubdotcom** [comment]
In that case, should the VMware Fusion be adjusted to a single core too? It's good to have the setting explicit since users are aware they can modify this

**Comment by khromov** [comment]
@hubdotcom You may be interested in the vagrant-faster plugin that can increase the specs automatically according to the performance specs of the host:
https://github.com/rdsubhas/vagrant-faster

**Comment by hubdotcom** [comment]
nice recommendation!

**Comment by hubdotcom** [comment]
Have adjusted the default cores to 1 on all installs

**Comment by jeremyfelt** [comment]
Being explicit is good. I like the idea of sticking to 1 core by default for VirtualBox. I wonder if that impacted some of the speed results. :)

**Pull request merged**
