### PR TITLE
Changes hyperv provider to a working one

### PR DESCRIPTION
**Pull request by roelveldhuizen**
By switching to this box VVV works again on Hyper-v.

Also solves #1082

### CODE REVIEW

**Comment by benlumia007** [comment]
so does the hyper-v works on VVV 2+, i got little confused reading all that stuff.

**Comment by tomjn** [comment]
If set up I guess, I can write a doc page on using hyper V if somebody fills me in with the details

**Comment by tomjn** [comment]
@benlumia007 I started WIP docs at https://github.com/Varying-Vagrant-Vagrants/varyingvagrantvagrants.org/pull/56 but as I'm not a Windows user I need feedback

**Comment by benlumia007** [comment]
@tomjn 

so after trying to enable Hyper V on my Microsoft Surface Pro 4, it still doesn't seem to wanting to find the box ericmann/trusty64, so I guess it still doesn't work.

**Comment by Viper007Bond** [comment]
Are you using the `develop` branch? `master` doesn't include this change. `phawxby/trusty64` is the correct box.

**Comment by benlumia007** [comment]
yes, I'm using the develop branch, instead of the stable tag,  so how do i change it to `phawxby/trusty64`

**Comment by tomjn** [comment]
It should know to use that box if the provider is setup as HyperV, `vagrant destroy` followed by å provision with the right provider setup might work

**Comment by benlumia007** [comment]
yeah so i did was `vagrant up --provider=hyperv` and its still trying to find that ericmann/trusty64 box.

**Comment by benlumia007** [comment]
well it seems its working, thanks guys

**Comment by benlumia007** [comment]
so it founded the box and i try to see if it works, and got to where it says  it was looking for vboxsf, assuming that its a guest addition for virtualbox. any idea on how i would avoid this

**Pull request merged**
