### PR TITLE
fix(db): importing when excluded

### PR DESCRIPTION
**Pull request by Mte90**
Fix https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2546

## Checks

* [x] I've updated the changelog.
* [x] I've tested this PR
* [x] This PR is for the `develop` branch not the `stable` branch.
* [x] This PR is complete and ready for review.

### CODE REVIEW

**Comment by Mte90** [comment]
Tested with the latest changes and is working to me with the new parameters

**Comment by tomjn** [comment]
@Mte90 we still need to account for backwards compatibility for when `general.db_restore` is a boolean not a struct, e.g.:

```yaml
general:
  db_restore: false
```

**Comment by tomjn** [comment]
A parameter under `db_restore` to act as its replacement makes sense, but I'm not sure what it should be named

**Review by tomjn — APPROVED** [review]

**Comment by Mte90** [comment]
> @Mte90 we still need to account for backwards compatibility for when `general.db_restore` is a boolean not a struct, e.g.:
> 
> ```yaml
> general:
>   db_restore: false
> ```

The only use of that parameter is in that script and this check if it is a bool https://github.com/Varying-Vagrant-Vagrants/VVV/blob/4c74fee6e4bc097cf76620671791c775be46b8b7/database/sql/import-sql.sh#L33

**Pull request merged**
