### PR TITLE
Change "global" phpcs provisioning to be more modern.

### PR DESCRIPTION
**Pull request by msaggiorato**
This change should allow composer v2 to be used across the guets VM, while also deprecating some old techniques for installing phpcs.

### CODE REVIEW

**Review by Mte90 — APPROVED** [review]
I tested and there are no errors and seems everything fine.

**Review by tomjn — CHANGES_REQUESTED** [review]
Needs changelog updates

**Comment by tomjn** [comment]
@msaggiorato I've tried pulling down the changes but every time I try to check out I get this:

```
From github.com:saucal/VVV
 * branch            upgrade-phpcs-install -> FETCH_HEAD
 * [new branch]      upgrade-phpcs-install -> saucal/upgrade-phpcs-install
fatal: Not possible to fast-forward, aborting.
```

Can you do the changes on the VVV repo in a branch rather than on a fork? I'm not sure what happened to the other repo to cause this

**Comment by msaggiorato** [comment]
That's weird, I'll push it to a branch here.

**Pull request closed without merging**
