### PR TITLE
set your GitHub token easily for Composer

### PR DESCRIPTION
**Pull request by cfoellmann**
Just create a simple text file named `provision/github.token` with only your gh token to automatically set the token for composer

### CODE REVIEW

**Comment by jeremyfelt** [comment]
Ooh, interesting.

**Comment by cfoellmann** [comment]
anyone else tested this?
It is pretty nice to have when working on VVV itself. The checkouts via composer is very slow once you reach the anonymous github api limit.

**Comment by khromov** [comment]
:+1: Very nice

**Comment by jeremyfelt** [comment]
Seems smart to me. I thought a bit about whether `/provision/` was the correct place for the toke file, but I think it makes sense in the end as other custom stuff is there and it's related directly to provisioning.

Thanks @cfoellmann!

**Pull request merged**
