### PR TITLE
Upgrade default PHP to v7.4

### PR DESCRIPTION
**Pull request by tomjn**
Changes the default PHP from 7.3 to 7.4

## Checks

* [x] I've updated the changelog.
* [x] I've tested this PR
* [x] This PR is for the `develop` branch not the `stable` branch.
* [x] This PR is complete and ready for review.

### CODE REVIEW

**Comment by Mte90** [comment]
As we are working on that maybe we can also implement https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2309

**Comment by msaggiorato** [comment]
As @Mte90 says, this new command seems like a good chance to set a specific php version as default.

It could open up a can of worms of support tho, when some specific PHP version make provisioners or stuff stop working.

**Comment by tomjn** [comment]
I don't think we should conflate upgrading 7.4 and making PHP default versions configurable. They aren't the same piece of work. I also having misgivings about making the default user configurable, it's a blunt force fix that doesn't address the actual problem, an X Y problem.

**Review by benlumia007 — APPROVED** [review]
looks good.

**Pull request merged**
