### PR TITLE
install additional NTP packages and restart the service

### PR DESCRIPTION
**Pull request by tomjn**
## Summary:

Installs additional NTP packages

## Checks

 - [ ] I've tested this PR with Vagrant **vXX** and VirtualBox **vXX** on **Operating System**
 - [x] This PR is for the `develop` branch not the `master` branch
 - [x] I've updated the changelog
 - [ ] This PR is complete and ready for review

### CODE REVIEW

**Comment by Mte90** [comment]
I can confirm those packages in VVV are not present

**Comment by tomjn** [comment]
We install the ntp package in the mean provisioner, does that not mean the
ntp service is available?

**Comment by Mte90** [comment]
NTP is to set the timezone but ntupdate sync that with ntp servers.

**Comment by tomjn** [comment]
closes #2006

**Pull request merged**
