### PR TITLE
Fix syhaml not working

### PR DESCRIPTION
**Pull request by msaggiorato**
Trying a fresh provision today, and shyaml wasn't installing.

After this, it provisions and work fine. Not sure of the details of the error (likely a change upstream somewhere).

### CODE REVIEW

**Comment by Mte90** [comment]
Strange because there are no new release of that package since 2018 https://github.com/0k/shyaml/releases

Also setuptools and wheel are needed to generate a pip package.

**Comment by msaggiorato** [comment]
Super strange indeed... Maybe I was hit with a bad cache somewhere?

Without doing this provision was definetely not working.

It's also definetely strange that nobody reported this yet.

**Comment by Mte90** [comment]
I am testing a provision and I don't see any error about shyaml.

**Comment by msaggiorato** [comment]
Are you trying completely from scratch? Destroying and provisioning?

Can you share the logs around shyaml installation?

**Comment by Mte90** [comment]
I did a provision on my machine, now trying with a vagrant destroy.
I will let you know.

**Comment by Mte90** [comment]
Ok so in a new box I got that error but when started working on custom-template and not during VVV.

The issue is one of the dependence of shyaml that require those packages.

**Review by Mte90 — APPROVED** [review]

**Pull request merged**
