### PR TITLE
Update my.cnf for innodb_file_per_table = 1

### LINKED ISSUE #537: Use innodb_file_per_table = 1 ?
Would it make sense to use Use innodb_file_per_table = 1 to split the DBs into separate files, whereby deleting a database might reclaim disk space or did moe the DBs out of the sync'd folder make that pointless?  

This was a tweak Eric Mann had proposed herw https://eamann.com/tech/varying-vagrants-evolved/ some time ago, but which I really liked.

### PR DESCRIPTION
**Pull request by jb510**
Fixes #537

### CODE REVIEW

**Comment by grappler** [comment]
There is a PR open for this. https://github.com/Varying-Vagrant-Vagrants/VVV/pull/538/files

**Comment by jeremyfelt** [comment]
Thanks, @jb510! #538 beat you by a couple days. :)

**Comment by jeremyfelt** [comment]
I swear the above open/close activity was not all me. Just twice! :)

I'm going to take a look at this tomorrow, @jb510. Thanks!

**Comment by jeremyfelt** [comment]
Ok, we're looking good here. Thanks @jb510!

**Pull request merged**
