### PR TITLE
WiP: Add docker provider support

### PR DESCRIPTION
**Pull request by glensc**
Adds [Docker Provider](https://www.vagrantup.com/docs/docker/) support.

To be used as:

```
$ vagrant up --provider=docker
```

### CODE REVIEW

**Comment by glensc** [comment]
can be merged as is i'm unlikely to finish this. but it's probably good staring ground for someone to continue

**Comment by cfoellmann** [comment]
I assume you meant 'closed'.
Maybe someone can pick this up if there is a need.

**Comment by glensc** [comment]
no, i did really mean "merge". "close" i can do myself too if i wanted.

if you just close, nobody will notice the PR, but if it's partially on master branch, someone may take it off from there.

**Comment by cfoellmann** [comment]
We do not merge anything unfinished into `master` or `develop`. These are working versions people use in their daily workflows. Nothing broken or unfinished will be merged there.

**Comment by glensc** [comment]
and then you have `provision/provision.sh` there, which looks to me lot of incomplete code. whatever. bye.

**Pull request closed without merging**
