### PR TITLE
fix-no-tty

### PR DESCRIPTION
**Pull request by cfoellmann**
fix suggested by @twisty7867 in #517

SEE: http://foo-o-rama.com/vagrant--stdin-is-not-a-tty--fix.html

### CODE REVIEW

**Comment by cfoellmann** [comment]
This works for me so far. Needs longer testing and more testers.

**Comment by HongPong** [comment]
I tried putting this fix at line 212 and it doesn't seem to fix it, still get the error 2x on bootup, but I am new to vagrant and might be doing something wrong in the testing process here.

**Comment by twisty7867** [comment]
@HongPong I'm curious to see your Vagrantfile and output. For me, it eliminates the error entirely *as long as it's the first provisioner that runs*. I am **obsessed** with getting zero red text.

**Comment by HongPong** [comment]
sure, i think i tried that too (as in it was the first statement below 'provisioning' comments)
Please see https://gist.github.com/korgroup/ad904f8727627c1ee852
https://gist.github.com/korgroup/4d9cfc98deebc2b9adb6

However I also had a transient error where i could not go into the www folder when i was inside the vagrant shell, it spit out a bunch of ???? marks when i tried to ls the /srv/www . Maybe this went away when i made a new local shell window? 
It's not doing that www problem right now, but the errors are still occurring regardless. This is my first day with vagrant and it's pretty nifty but a little tricky to understand everything.

**Comment by twisty7867** [comment]
Rather than cluttering up this PR with our discussion, I'd be happy to follow up with you via email if you want some help. I think the issue is that your VM was already provisioned and you just a `vagrant reload`. Run `vagrant provision` and you should see something like this in the output:
```
==> default: Running provisioner: fix-no-tty (shell)...
    default: Running: inline script
```
Once you see that, nevermore should you see the "not a tty" message. Depending on what your other provisioning scripts do, you might get a similar message from `dpkg-reconfigure`. The fix for that (and just a best practice in general) is to provide the answers up front using `dpkg-preconfigure` or `debconf-set-selections`.

**Comment by HongPong** [comment]
thanks @twisty7867 that was the right advice, it did kick in and this patch seems to work quite well indeed.

**Comment by jeremyfelt** [comment]
This is great stuff. Love getting rid of that error. :)

@twisty7867 Are you good with including this with VVV under the MIT License? It looks like the origin is straight from [your post](http://foo-o-rama.com/vagrant--stdin-is-not-a-tty--fix.html).

Thanks!

**Comment by twisty7867** [comment]
Yes, feel free. I'll update my page to indicate that I consider the code snippet to be in the public domain.

**Comment by jeremyfelt** [comment]
Great, thanks!

**Comment by laite** [comment]
I'm getting an error with this commit when running `vagrant up` for the first time.

```
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The 'fix-no-tty' provisioner could not be found.
```

Vagrant 1.6.3 on Debian unstable (sid) x64. Building from current `master` branch works.

**Comment by twisty7867** [comment]
Named provisioners require vagrant 1.7 or better. You can upgrade or remove the name and new type argument, leaving just the "shell" value instead.

**Comment by michaelbeil** [comment]
VVV requires Vagrant 1.7.x: https://github.com/Varying-Vagrant-Vagrants/VVV/blame/develop/README.md#L55.

**Comment by laite** [comment]
Thanks, it seems I noticed that too late. Sorry about that.

**Pull request merged**
