### PR TITLE
Disable backups by default

### PR DESCRIPTION
**Pull request by tomjn**
Disables backup and restore of the database by  default

## Checks

* [ ] I've updated the changelog.
* [ ] I've tested this PR
* [x] This PR is for the `develop` branch not the `stable` branch.
* [ ] This PR is complete and ready for review.

### CODE REVIEW

**Comment by msaggiorato** [comment]
What's the reasoning for this? I can see restore being disabled by default, but why disable backups?

**Comment by tomjn** [comment]
> What's the reasoning for this? I can see restore being disabled by default, but why disable backups?

Users can run these manually or turn them back on, it seems that people are provisioning with monumentally huge databases and see multi-hour provisioning as just a fact of life. A provision shouldn't take longer than 10 minutes.

When we have more granular backup options we can rethink this, but we've been saying that for a while and nobody has stepped up to implement it.

Also, the original purpose of this was so that you could `vagrant destroy` then `vagrant up` regularly, but we no longer expect this.

**Comment by Mte90** [comment]
It makes sense indeed if someone does often a vagrant destroy and it isn't the majority of the users.
I agree with that change.

**Comment by tomjn** [comment]
Ideally we  would  implement part  of this:

https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2225

**Review by Mte90 — APPROVED** [review]

**Comment by evertiro** [comment]
@tomjn just making sure this hasn't been forgotten. It's been almost a month since it was approved!

**Comment by tomjn** [comment]
@evertiro I was never needed for this to be merged

**Pull request closed without merging**
