### PR TITLE
Fix 2502

### PR DESCRIPTION
**Pull request by Mte90**
Ref: https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2502

## Checks

* [ ] I've updated the changelog.
* [ ] I've tested this PR
* [x] This PR is for the `develop` branch not the `stable` branch.
* [ ] This PR is complete and ready for review.

### CODE REVIEW

**Comment by tomjn** [comment]
@Mte90 if you use `get-type` instead you can test the value of `db_backup`, if it's true/false you'll get `bool` back, if it's got sub-values you'll get `struct`

**Comment by tomjn** [comment]
Also there's parameter expansion which will need quote wrapping

**Comment by Mte90** [comment]
I should be able to improve the code using the quiet parameter of shyaml.

**Comment by emgk** [comment]
I've tested the changes with all possible cases using `vagrant_halt` script, seems to be working fine, thank you guys.

**Review by tomjn — APPROVED** [review]
👍🏻

**Pull request merged**
