### PR TITLE
Add Adapter and IP list to default page

### LINKED ISSUE #730: Create new page to display public_network IP address
Lots of great discussion in #566 helped me understand how to use the **public_network** property properly.

@jpry's notes about `vagrant ssh` / `ifconfig` to determine the public_network IP address are great

I'm wondering if we could create a page at something like http://vvv.dev/public-ip/ which could display either:

> This site is not available on any public IP, see how to configure public_network

or

> Your public IP is: <display IP address here>

I'm happy to look into this but I wanted to float the idea first.

### PR DESCRIPTION
**Pull request by salcode**
Add adapters with assigned IP addreses to output on the default page

Fixes #730

### CODE REVIEW

**Comment by salcode** [comment]
I wanted to keep this first pass simple.

I think it makes sense to filter out the __eth0__ adapter since on my Mac with Virtualbox, the relevant IP addresses are always assigned to __eth1__ or higher.

**Comment by jeremyfelt** [comment]
Oooh, slick. Sorry for taking 27 days to see this. :)

I'm going to mess around with it, but I like the idea.

**Comment by salcode** [comment]
@jeremyfelt Great, I'd love another set of eyes on this and some fresh ideas.  Thanks.

**Comment by salcode** [comment]
I've updated this PR to output a list of the IPs and then test each one with an AJAX call.

While this will detect localhost (127.0.0.1), it does not detect your local IP address (e.g. 192.168.50.1).  

The User's local IP address is particularly relevant if you're using Port Forwarding rather than the Public Network option.  It appears you can detect your local IP address from the browser in Chrome and Firefox, see http://net.ipcalf.com/, which would be great but adds complexity.  I think it makes sense to get this base functionality first and then look at adding local IP address detection in a future commit.

**Comment by tomjn** [comment]
I like this idea too, but it conflicts with the new VVV 2 changes :(

**Comment by tomjn** [comment]
I'm closing this out as the dashboard was moved to a separate repo

**Pull request closed without merging**
