### PR TITLE
Force 64bit in vagrantfile under virtualbox

### PR DESCRIPTION
**Pull request by tomjn**
Based on https://github.com/laravel/homestead/pull/63

## Checks

* [x] I've updated the changelog.
* [ ] I've tested this PR
* [x] This PR is for the `develop` branch not the `stable` branch.
* [ ] This PR is complete and ready for review.

### CODE REVIEW

**Review by evertiro — DISMISSED** [review]
Fundamentally, I don't see an issue here. Obviously, I can't test it, but it doesn't break anything for me and doesn't appear to have any typos.

**Comment by evertiro** [comment]
Consider my approval provisional, this needs a proper review from someone who can use VirtualBox.

**Comment by Mte90** [comment]
A `vagrant destroy` should be the right way to test it.

**Review by Mte90 — DISMISSED** [review]
tried with a vagrant destroy and up and everything worked

**Pull request merged**
