### PR TITLE
Update broken license link

### PR DESCRIPTION
**Pull request by michaelbeil**
squashes #620

### CODE REVIEW

**Comment by jeremyfelt** [comment]
Great catch, thanks @michaelbeil!

**Comment by michaelbeil** [comment]
Sure thing @jeremyfelt! Need me to add myself to contributors?

**Comment by jeremyfelt** [comment]
Nope, already got you in shortly after. :smile:

**Comment by michaelbeil** [comment]
ah fast on the trigger :smiley:.

**Pull request merged**
