### PR TITLE
Fix unbound variable

### PR DESCRIPTION
**Pull request by Mte90**
Ref: https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2613

## Checks

* [ ] I've updated the changelog.
* [x] I've tested this PR
* [x] This PR is for the `develop` branch not the `stable` branch.
* [x] This PR is complete and ready for review.

### CODE REVIEW

**Review by tomjn — DISMISSED** [review]
Nice catch!

**Comment by Mte90** [comment]
I saw the error and some issues on backup without a log, so...

This fix :-)

**Comment by tomjn** [comment]
@Mte90 lets get this in the changelog and then we can merge

**Comment by tomjn** [comment]
@Mte90 we don't need this in `db_restore` too do we?

**Comment by Mte90** [comment]
I checked when I did the PR and I didn't see the error with that script

**Pull request merged**
