### PR TITLE
Fix #1654, auto install vagrant plugin

### LINKED ISSUE #1654: Support Vagrant 2.2.0 for autodownload plugins
## Expected Behavior
Vagrant auto download the hosts plugin so is a step already done

## Current Behavior
Now is manually

## Possible Solution
https://www.hashicorp.com/blog/vagrant-2-2-0

Vagrant 2.2.0 support a new parameter where is possible to define the plugin and he will try to download and install automatically.

### PR DESCRIPTION
**Pull request by Mte90**
## Summary:

https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1654

## Checks

 - [x] I've tested this PR with Vagrant **vXX** and VirtualBox **vXX** on **Operating System**
 - [x] This PR is for the `develop` branch not the `master` branch
 - [x] I've updated the changelog
 - [x] This PR is complete and ready for review

### CODE REVIEW

**Comment by tomjn** [comment]
I don't know about adding vbguest, but have we tested how this would work with the contributor day installs? We spent a good hour trying to download a 10kb gem file to peoples machines over the wifi at WCEU last year so it needs to be 100% offline

**Comment by Mte90** [comment]
If the packages are already installed they are not downloaded from vagrant.
If during contributor days people will follow the instructions this problem doesn't happen.
We can remove the vbguest that is not mandatory compared to the hosts in case.

Another option looking at the docs is https://www.vagrantup.com/docs/vagrantfile/vagrant_settings.html#entry_point that let to configure the path where is the plugin file so is not downloaded.

**Comment by tomjn** [comment]
hmm does that expect a gem file or a folder with ruby files? The docs on entry point are a little sparse

**Comment by Mte90** [comment]
screenshot_20190219_154012
With this new code is using a local gem file that I put in the VVV folder.
I think that is interesting for us so we can do our version of the hostsupdater plugin that execute the hook early.

**Comment by tomjn** [comment]
Where did the gem file get placed?

**Comment by Mte90** [comment]
I put that file in the same folder of the `VagrantFile` but it is possible to configure the path.
We can do also that the CD-USB generator put that file in the VVV folder and avoid a step during contributor days.

**Comment by Mte90** [comment]
I am doing few tests and seems that there are problems when `vagrant up` is done in  a subfolder after the automatic installer.
I am doing more analysis on that.

**Comment by tomjn** [comment]
@Mte90 you can use `vagrant_dir = File.expand_path(File.dirname(__FILE__))`, look at how the config file is being loaded

**Comment by Mte90** [comment]
I switched to another version because there are problems.
First problem seems that using the native vagrant system the package is installed also if it is not the root folder but on starting again there is an error about not possible to load the plugin installed. Also this will install the package as local for that vagrant instance and not global.

So my solution is:

* if the package is not installed
  * if local file available install it globally
  * else install from internet

We can do another package and call it in another way, also because seems that the original is like abandoned and upload in rubygems as second step.

**Comment by Mte90** [comment]
I am already using `vagrant_dir` but seems a bug in vagrant because the path printed is right and also absolute.

**Comment by tomjn** [comment]
@Mte90 is that why you use a `system` call instead of `config.vagrant.plugins = {"vagrant-hostsupdater" => {"entry_point" => File.join(vagrant_dir, 'vagrant-hostsupdater.gem' )}}`?

**Comment by Mte90** [comment]
I removed because there is a bug in vagrant.
The plugin is installed rightly locally only for the project but at the next run there is an error that say that cannot find the folder.
If you try you can see it, instead if installed globallythe problem doesn't happen.

**Comment by tomjn** [comment]
but then don't we have to run the vagrant file a second time so the plugin is loaded?

**Comment by tomjn** [comment]
And is there a vagrant issue we can refer to for the bug?

**Comment by Mte90** [comment]
Using this method or the native one is always required to restart vagrant. 
The command is closed and alert for it.
About the vagrant bug I didn't had time to do more tests, if someone can check it too in a way to verify if it is me or a vagrant bug.

**Comment by tomjn** [comment]
Tbh Id rather not do this then if it requires the vagrant file be run again
for hosts updater

**Comment by Mte90** [comment]
It is the standard behaviour of `vagrant up` to be executed again if we use the native system.
Anyway there is a big alert to execute it again, the only other option is to do a shell script that before install the plugin and later execute vagrant but I don't think that is the best solution.

**Comment by tomjn** [comment]
This makes hostupdater a requirement ( which most already consider it to be ), I've no qualms with that, the only other thing is that it also makes Vagrant 2.2 a minimum requirement

**Pull request merged**
