### PR TITLE
Fixes to HyperV

### PR DESCRIPTION
**Pull request by tomjn**
Removes the mounting options, fixes the ubuntu user unknown problem, adds a performance parameter to improve provisioning speeds, comments out the SMB shares part, switches to the bento projects ubuntu 14 box, and fixes a mounting issue related to inconsistent use of trailing slashes in folder names

### CODE REVIEW

**Comment by tomjn** [comment]
Related to #1617 #1616 and #1615

**Comment by tomjn** [comment]
This seems to fix some of the problems encountered but a provision under hyperv here throws up read and write permission problems with the mounted folders

**Comment by tomjn** [comment]
@LoreleiAurora I could do with a second opinion on how to wrangle the permissions, as well as valid mount options

**Comment by benlumia007** [comment]
@tomjn and @LoreleiAurora 
Does this need more testing. I apparently ditched Windows and went on using Ubuntu and MacBook, but I do have a Surface Pro 4 as of right now to test hyper-v

**Comment by tomjn** [comment]
@benlumia007 so right now this doesn't provision because the shared folders get mounted but the packages can't write to it, so package installation fails on the first provision. It's further than `master` or `develop` get, and it's fixable, but I'm unsure which user or group to mount it as ( or why most non virtualbox ubuntu boxes lack an `ubuntu` user to begin with )

**Pull request merged**
