### PR TITLE
Tomjn/remove/vagrantshare

### LINKED ISSUE #1776: Copy homebin config files and vvv version and config
These files are currently mounted to `/vagrant` but instead they should be copied into the VM at `/vagrant` so that we can remove the `/vagrant` mount

### LINKED ISSUE #1777: Remove /vagrant mount
By default Vagrant mounts the folder with the vagrant file on to `/vagrant` inside the guest VM. This is bad as we get overlapping shared folders, which causes problems.

We need to break this dependency and eliminate this shared folder, Number 1 priority

### PR DESCRIPTION
**Pull request by tomjn**
## Summary:

Removes the `/vagrant` share folder

closes #1777 closes #1776 

## Checks

 - [x] I've tested this PR with Vagrant **v2.2.4** and VirtualBox **v6.0.6** on **MacOS**
 - [x] This PR is for the `develop` branch not the `master` branch
 - [x] I've updated the changelog
 - [x] This PR is complete and ready for review

### CODE REVIEW

**Comment by tomjn** [comment]
This will fail as is, it needs PR #1783 to be merged, the TLS CA to be adjusted, and it needs the `version` and `vvv-custom.yml` files to be sorted out

**Comment by Mte90** [comment]
immagine
I am getting this error

**Comment by Mte90** [comment]
I think that also:

- https://github.com/Varying-Vagrant-Vagrants/VVV/blob/2264eed057771726b1124db775baca74ab33d462/config/homebin/db_backup#L6
- https://github.com/Varying-Vagrant-Vagrants/VVV/blob/6f4ec3d7bf35166107e06cba6ed94c03f5d917d5/provision/provision-site.sh#L13
- https://github.com/Varying-Vagrant-Vagrants/VVV/blob/d36d979f9b85a6f134f0558da369892ad8114abb/config/bash_profile#L69
- https://github.com/Varying-Vagrant-Vagrants/VVV/blob/84a14741eb714a6b78010e36c3cbc0f8829723f3/database/sql/import-sql.sh#L23

I am getting this error:
immagine

But investigating is not getting any hints:
immagine

**Comment by Mte90** [comment]
I don't know why but seems that I changed another comment in the ticket with some other issues https://github.com/Varying-Vagrant-Vagrants/VVV/pull/1784#issuecomment-490506137

**Comment by tomjn** [comment]
For some reason this doesn't contain the changes from the other PR, unsure why

**Comment by Mte90** [comment]
Tried again but I am still getting issues with nginx.

**Comment by tomjn** [comment]
I've gone through, changed things in a few additional repos to account for things like site provisioners relying on `/vagrant/certificates` etc, and it's provisioned ok here locally

**Comment by tomjn** [comment]
Also closes #1789

**Comment by IanMezza** [comment]
Already tried this one on a clean install. This worked for me

**Comment by tomjn** [comment]
@Mte90 does this work with the last few commits?

**Comment by Mte90** [comment]
I am trying with another VVV install but I got this error after a vagrant destroy with a vagrant up:
immagine

**Comment by Mte90** [comment]
I got also:
immagine

**Comment by Mte90** [comment]
Anyway now seems that everything works.
I don't know about this errors if we can do something for them

**Comment by Mte90** [comment]
Works :-D

**Comment by tomjn** [comment]
I added 2 amended updates to the Ubuntu 14 detection message:

If DB backups are in the backups folder:

Screenshot 2019-05-09 at 16 16 09

If they aren't:

Screenshot 2019-05-09 at 16 17 00

**Pull request merged**
