### PR TITLE
add bootstrap dashboard that picks up added sites

### PR DESCRIPTION
**Pull request by Tarendai**
Upgrades the default dashboard to:

 - Look in the /srv/www folder for added sites and list them alongside the defaults
 - Descriptions of built in tools
 - A link to the documentation wiki
 - Bootstrap 3 styling

screen shot 2014-04-20 at 21 46 11

### CODE REVIEW

**Comment by cfoellmann** [comment]
Can we pick this up again?
I would really love for this to be implemented. Maybe we can "just" grab @topdown's package in the provision process. It looks pretty good to me.

**Comment by Tarendai** [comment]
Agreed, @topdown's package looks good from the screenshot

**Comment by michaelbeil** [comment]
+1 on including @topdown's https://github.com/topdown/VVV-Dashboard.

**Comment by cfoellmann** [comment]
You can auto setup @topdown's vvv-dashboard via this vvv-site https://github.com/cfoellmann/vvv-sites/tree/master/vvv-dashboard

**Comment by cfoellmann** [comment]
"people" seem to like @topdown's dashboard and we can provision it automatically. SEE: #609 
This way @topdown has full control (but also the responsibility) to maintain the dashboard.

**Comment by jeremyfelt** [comment]
Leaving the same comment from #609, sorry for taking so long to fully address this.

------------------------
I love all these custom dashboards, so much great stuff. I'd rather not tie VVV directly into any of them at the moment. I think what we have is basic and ugly, and that's fine. I can definitely see adding a section in the README (more visible than the wiki) with a list of dashboards similar to our [helpful extensions](https://github.com/Varying-Vagrant-Vagrants/VVV#helpful-extensions) section. It may even make sense to add a small note to the default dashboard to make it more obvious that something custom can be installed.

I'm absolutely okay to make any changes that make it easier to distribute a custom dashboard, though it seems like the current model works pretty well.

**Pull request closed without merging**
