### PR TITLE
Switch to NodeSource for NodeJS packages

### PR DESCRIPTION
**Pull request by thebrandonallen**
Some of the WP node modules and their dependencies are beginning to complain about our outdated versions of NodeJS and npm. NodeSource seems to be the new standard for up-to-date NodeJS packages.

I've taken the conservative approach and chosen NodeJS v0.12.

Note, if someone runs `apt-get update` after a `vagrant provision` without first running `vagrant destroy`, apt-get will complain about not having the appropriate key for the nodesource packages. I'm not sure what the appropriate way to handle this. It may just be adding a something to the release notes saying to run `wget -qO- https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -` if one experiences this issue.

### CODE REVIEW

**Comment by ntwb** [comment]
This and #863 is working great :+1:

**Comment by thebrandonallen** [comment]
Updated to NodeJS 4.x LTS. I fixed locally but never pushed the change ¯\_(ツ)_/¯

**Comment by jeremyfelt** [comment]
We're also close on this once we get a few decisions locked down in #562.

**Comment by thebrandonallen** [comment]
I've merged the `develop` branch to resolve conflicts.

**Comment by jeremyfelt** [comment]
With this PR, I'm currently getting:

```
vagrant@vvv:~$ node --version
v4.5.0
vagrant@vvv:~$ npm --version
3.10.6
vagrant@vvv:~$ nvm --version
0.31.4
```

Great stuff, thanks @thebrandonallen!

**Pull request merged**
